[package]
name = "vest_lib2"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["alloc", "vstd/std"]
alloc = ["vstd/alloc"]

[dependencies]
vstd = { version = "=0.0.0-2026-08-23-0033", default-features = false }

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--expand-errors"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(verus_only)", 'cfg(verus_keep_ghost)'] }
