// @generated by vps-asn1 from ASN.1 module `SequenceWidth16`.
// Generated formats parse and serialize BER.
#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use vps_lib::asn1::*;
use vps_lib::asn1::der_ord::{DerOrd, DerState};
use vps_lib::asn1::disjoint::HasAsn1Start;
use vps_lib::asn1::ber::{AnyTlvFmt, BitStringTlvFmt, BmpStringTlvFmt, BoolTlvFmt, DefaultFmt, Enumerated16TlvFmt, EnumeratedTlvFmt, Explicit, ExplicitFmt, GeneralizedTimeTlvFmt, Ia5StringTlvFmt, Implicit, ImplicitFmt, Integer16TlvFmt, Integer8TlvFmt, IntegerTlvFmt, NullTlvFmt, ObjectIdentifierTlvFmt, OctetStringTlvFmt, NumericStringTlvFmt, PrintableStringTlvFmt, RealTlvFmt, SequenceFmt, SequenceOfFmt, SetOfTlvFmt, TeletexStringTlvFmt, UniversalStringTlvFmt, UtcTimeTlvFmt, Utf8StringTlvFmt, ANY, BIT_STRING, BMP_STRING, BOOLEAN, CHOICE, DEFAULT, ENUMERATED, ENUMERATED16, EXPLICIT, EXPLICIT_APPLICATION, EXPLICIT_PRIVATE, GENERALIZED_TIME, IA5_STRING, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, INTEGER, INTEGER16, INTEGER8, NULL, NUMERIC_STRING, OBJECT_IDENTIFIER, OCTET_STRING, OPTIONAL, PRINTABLE_STRING, REAL, REQUIRED, SEQUENCE, SEQUENCE_OF, SET_OF, TELETEX_STRING, UNIVERSAL_STRING, UTC_TIME, UTF8_STRING};
use vps_lib::asn1::ber::{BerEndFmt, BER_END};
use vps_lib::combinators::mapped::spec::{BiMap, SpecMap};
use vps_lib::combinators::*;
use vps_lib::combinators::Eof;
use Sum::Inl as L;
use Sum::Inr as R;
use vps_lib::core::exec::fns::{Map, Pred};
use vps_lib::core::exec::output::OutputBuf;
use vps_lib::core::exec::parser::{PResult, Parser};
use vps_lib::core::exec::serializer::{ByteLen, PreSerializeError, Prepare, Serializer};
use vps_lib::core::proof::*;
use vps_lib::core::spec::*;
use vstd::prelude::*;

verus! {

/// Value type for ASN.1 `AutomationSequence`.
pub struct AutomationSequence {
    pub field0: Option<bool>,
    pub field1: bool,
    pub field2: bool,
    pub field3: Option<bool>,
    pub field4: bool,
    pub field5: bool,
    pub field6: Option<bool>,
    pub field7: bool,
    pub field8: bool,
    pub field9: Option<bool>,
    pub field10: bool,
    pub field11: bool,
    pub field12: Option<bool>,
    pub field13: bool,
    pub field14: bool,
    pub field15: Option<bool>,
}

#[verifier::ext_equal]
pub struct AutomationSequenceSpec<T0 = Option<bool>, T1 = bool, T2 = bool, T3 = Option<bool>, T4 = bool, T5 = bool, T6 = Option<bool>, T7 = bool, T8 = bool, T9 = Option<bool>, T10 = bool, T11 = bool, T12 = Option<bool>, T13 = bool, T14 = bool, T15 = Option<bool>> {
    pub field0: T0,
    pub field1: T1,
    pub field2: T2,
    pub field3: T3,
    pub field4: T4,
    pub field5: T5,
    pub field6: T6,
    pub field7: T7,
    pub field8: T8,
    pub field9: T9,
    pub field10: T10,
    pub field11: T11,
    pub field12: T12,
    pub field13: T13,
    pub field14: T14,
    pub field15: T15,
}

impl DeepView for AutomationSequence {
    type V = AutomationSequenceSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        AutomationSequenceSpec {
            field0: self.field0.deep_view(),
            field1: self.field1.deep_view(),
            field2: self.field2.deep_view(),
            field3: self.field3.deep_view(),
            field4: self.field4.deep_view(),
            field5: self.field5.deep_view(),
            field6: self.field6.deep_view(),
            field7: self.field7.deep_view(),
            field8: self.field8.deep_view(),
            field9: self.field9.deep_view(),
            field10: self.field10.deep_view(),
            field11: self.field11.deep_view(),
            field12: self.field12.deep_view(),
            field13: self.field13.deep_view(),
            field14: self.field14.deep_view(),
            field15: self.field15.deep_view(),
        }
    }
}

#[derive(Clone, Copy)]
pub struct AutomationSequenceForward;
#[derive(Clone, Copy)]
pub struct AutomationSequenceReverse;

impl<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> AutomationSequenceSpec<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, (T2, (T3, (T4, (T5, (T6, (T7, (T8, (T9, (T10, (T11, (T12, (T13, (T14, (T15, ()))))))))))))))))) -> Self {
        let (field0, (field1, (field2, (field3, (field4, (field5, (field6, (field7, (field8, (field9, (field10, (field11, (field12, (field13, (field14, (field15, _end)))))))))))))))) = input;
        Self {
            field0,
            field1,
            field2,
            field3,
            field4,
            field5,
            field6,
            field7,
            field8,
            field9,
            field10,
            field11,
            field12,
            field13,
            field14,
            field15,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, (T2, (T3, (T4, (T5, (T6, (T7, (T8, (T9, (T10, (T11, (T12, (T13, (T14, (T15, ())))))))))))))))) {
        (self.field0, (self.field1, (self.field2, (self.field3, (self.field4, (self.field5, (self.field6, (self.field7, (self.field8, (self.field9, (self.field10, (self.field11, (self.field12, (self.field13, (self.field14, (self.field15, ()))))))))))))))))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(AutomationSequenceSpec::from_structural);
        reveal(AutomationSequenceSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, (T2, (T3, (T4, (T5, (T6, (T7, (T8, (T9, (T10, (T11, (T12, (T13, (T14, (T15, ())))))))))))))))))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(AutomationSequenceSpec::from_structural);
        reveal(AutomationSequenceSpec::into_structural);
    }
}

impl SpecMap for AutomationSequenceForward {
    type Input = (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, ()))))))))))))))));
    type Output = AutomationSequenceSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        AutomationSequenceSpec::from_structural(input)
    }
}

impl SpecMap for AutomationSequenceReverse {
    type Input = AutomationSequenceSpec;
    type Output = (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, ()))))))))))))))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl Map<(Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, ()))))))))))))))))> for AutomationSequenceForward {
    type O = AutomationSequence;
    fn map(&self, input: (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, (bool, (bool, (Option<bool>, ()))))))))))))))))) -> (value: Self::O) {
        proof {
            reveal(<AutomationSequence as DeepView>::deep_view);
            reveal(AutomationSequenceSpec::from_structural);
        }
        let (field0, (field1, (field2, (field3, (field4, (field5, (field6, (field7, (field8, (field9, (field10, (field11, (field12, (field13, (field14, (field15, _end)))))))))))))))) = input;
        AutomationSequence {
            field0,
            field1,
            field2,
            field3,
            field4,
            field5,
            field6,
            field7,
            field8,
            field9,
            field10,
            field11,
            field12,
            field13,
            field14,
            field15,
        }
    }
}

impl<'x> Map<&'x AutomationSequence> for AutomationSequenceReverse {
    type O = (Option<&'x bool>, (bool, (&'x bool, (Option<&'x bool>, (bool, (&'x bool, (Option<&'x bool>, (bool, (&'x bool, (Option<&'x bool>, (bool, (&'x bool, (Option<&'x bool>, (bool, (&'x bool, (Option<&'x bool>, ()))))))))))))))));
    fn map(&self, value: &'x AutomationSequence) -> (output: Self::O) {
        proof {
            reveal(<AutomationSequence as DeepView>::deep_view);
            reveal(AutomationSequenceSpec::into_structural);
        }
        (value.field0.as_ref(), (value.field1, (&value.field2, (value.field3.as_ref(), (value.field4, (&value.field5, (value.field6.as_ref(), (value.field7, (&value.field8, (value.field9.as_ref(), (value.field10, (&value.field11, (value.field12.as_ref(), (value.field13, (&value.field14, (value.field15.as_ref(), ()))))))))))))))))
    }
}

/// BER format for ASN.1 `AutomationSequence`.
type AUTOMATION_SEQUENCE__ = Mapped<SequenceFmt<Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ImplicitFmt<Ref<BoolTlvFmt>>, BerEndFmt>>>>>>>>>>>>>>>>>, BiMap<AutomationSequenceForward, AutomationSequenceReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct AUTOMATION_SEQUENCE(pub Class, pub u64);
impl AUTOMATION_SEQUENCE {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> AUTOMATION_SEQUENCE__
        returns
            (
                Mapped {
                    inner:
                        SEQUENCE(
                            OPTIONAL(IMPLICIT(0u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(1u64, BOOLEAN), false,
                            REQUIRED(IMPLICIT(2u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(3u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(4u64, BOOLEAN), false,
                            REQUIRED(IMPLICIT(5u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(6u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(7u64, BOOLEAN), false,
                            REQUIRED(IMPLICIT(8u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(9u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(10u64, BOOLEAN), false,
                            REQUIRED(IMPLICIT(11u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(12u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(13u64, BOOLEAN), false,
                            REQUIRED(IMPLICIT(14u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(15u64, Ref(BOOLEAN)),
                            BER_END)))))))))))))))),
                        ),
                    mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
                }
            ),
    {
        Mapped {
            inner:
                SEQUENCE(
                    OPTIONAL(IMPLICIT(0u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(1u64, BOOLEAN), false,
                    REQUIRED(IMPLICIT(2u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(3u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(4u64, BOOLEAN), false,
                    REQUIRED(IMPLICIT(5u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(6u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(7u64, BOOLEAN), false,
                    REQUIRED(IMPLICIT(8u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(9u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(10u64, BOOLEAN), false,
                    REQUIRED(IMPLICIT(11u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(12u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(13u64, BOOLEAN), false,
                    REQUIRED(IMPLICIT(14u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(15u64, Ref(BOOLEAN)),
                    BER_END)))))))))))))))),
                ),
            mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
        }
    }
}


} // verus!

mod __impl_automation_sequence {
    use super::*;

    vps_lib::impl_ber!(tagged(true), owned, AUTOMATION_SEQUENCE, AUTOMATION_SEQUENCE__, AutomationSequenceSpec, AutomationSequence, AutomationSequenceForward, AutomationSequenceReverse);
}
