[book]
authors = ["The Vest authors"]
language = "en"
src = "guide/src"
title = "Vest Documentation"

[build]
build-dir = "docs/guide"
create-missing = false

[output.html]
git-repository-url = "https://github.com/secure-foundations/vest"
site-url = "/vest/guide/"
additional-css = ["theme/vest-highlight.css"]
additional-js = ["theme/vest-highlight.js"]
