[workspace]
members = [
    "vest",
    "vest_lib",
    "vest_asn1",
    "vest_asn1/vendor/synta-codegen",
    "vest_tests",
    "vest_asn1_tests",
    "vest_dev",
]
default-members = ["vest", "vest_lib", "vest_asn1"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/secure-foundations/vest"

[workspace.dependencies]
vstd = { version = "=0.0.0-2026-08-23-0033", default-features = false }
vest_lib = { path = "vest_lib", default-features = false }

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
