mod triple {
    // This module includes the code generated by the build script from src/triple.vest
    // The generated file is placed in OUT_DIR/triple.rs by build.rs
    include!(concat!(env!("OUT_DIR"), "/triple.rs"));

}

use crate::triple::*;
use vest_lib::properties::SecureSpecCombinator;
use vest_lib::properties::SpecCombinator;
use vstd::prelude::*;

verus! {

fn main() {
    let fixed = [0x55, 0x77];
    let trip = Triple { a: 0x41, b: &fixed, c: 0xFFFF_FFFF_FFFF_FFFF };
    // let varied = [0x55, 0x77, 0x88];
    // let trip = Triple { a: 0x03, c: 0xFFFF_FFFF_FFFF_FFFF, d: &varied };
    let trip_len = triple_len(&trip);
    let mut bytes = vec![0u8; trip_len];
    let result = serialize_triple(&trip, &mut bytes, 0);
    match result {

        Ok(num_bytes) => {
            assert(bytes.len() == num_bytes);
            assert(num_bytes == 11);
            // assert(num_bytes == 12);
            
        },
        Err(_) => return,
    }
    let new_trip = parse_triple(&bytes);
    match new_trip {
        Ok((num_bytes, new_trip)) => {
            proof {
                spec_triple().theorem_serialize_parse_roundtrip(trip@);
            }
            assert(new_trip.a == 0x41);
            // assert(new_trip.a == 0x03);
        },
        Err(_) => (),
    }
}

} // verus!
