// @generated by vestasn1 from ASN.1 module `Fixture`.
// Generated formats parse and serialize DER.

use vest_lib2::asn1::*;
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Flag = bool;
pub type FlagSpec = bool;

pub type Count<'a> = vest_lib2::asn1::Integer<'a>;
pub type CountSpec = int;

pub type Payload<'a> = &'a [u8];
pub type PayloadSpec = Seq<u8>;

/// Value type for ASN.1 `Header`.
pub struct Header<'a> {
    pub flag: Flag,
    pub count: Count<'a>,
}

#[verifier::ext_equal]
pub struct HeaderSpec {
    pub flag: FlagSpec,
    pub count: CountSpec,
}

impl<'a> DeepView for Header<'a> {
    type V = HeaderSpec;
    open spec fn deep_view(&self) -> Self::V {
        HeaderSpec {
            flag: self.flag.deep_view(),
            count: self.count.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Envelope`.
pub struct Envelope<'a> {
    pub header: Header<'a>,
    pub payload: Option<Payload<'a>>,
}

#[verifier::ext_equal]
pub struct EnvelopeSpec {
    pub header: HeaderSpec,
    pub payload: Option<PayloadSpec>,
}

impl<'a> DeepView for Envelope<'a> {
    type V = EnvelopeSpec;
    open spec fn deep_view(&self) -> Self::V {
        EnvelopeSpec {
            header: self.header.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

pub type Envelopes<'a> = Vec<Envelope<'a>>;
pub type EnvelopesSpec = Seq<EnvelopeSpec>;

/// Value type for ASN.1 `Features`.
pub struct Features {
    pub enabled: Flag,
    pub visible: bool,
}

#[verifier::ext_equal]
pub struct FeaturesSpec {
    pub enabled: FlagSpec,
    pub visible: bool,
}

impl DeepView for Features {
    type V = FeaturesSpec;
    open spec fn deep_view(&self) -> Self::V {
        FeaturesSpec {
            enabled: self.enabled.deep_view(),
            visible: self.visible.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Selection`.
pub enum Selection<'a> {
    Flag(Flag),
    Payload(Payload<'a>),
}

#[verifier::ext_equal]
pub enum SelectionSpec {
    Flag(FlagSpec),
    Payload(PayloadSpec),
}

impl<'a> DeepView for Selection<'a> {
    type V = SelectionSpec;
    open spec fn deep_view(&self) -> Self::V {
        match self {
            Selection::Flag(value) => SelectionSpec::Flag(value.deep_view()),
            Selection::Payload(value) => SelectionSpec::Payload(value.deep_view()),
        }
    }
}

/// Value type for ASN.1 `ChoiceEnvelope`.
pub struct ChoiceEnvelope<'a> {
    pub selection: Option<Selection<'a>>,
}

#[verifier::ext_equal]
pub struct ChoiceEnvelopeSpec {
    pub selection: Option<SelectionSpec>,
}

impl<'a> DeepView for ChoiceEnvelope<'a> {
    type V = ChoiceEnvelopeSpec;
    open spec fn deep_view(&self) -> Self::V {
        ChoiceEnvelopeSpec {
            selection: self.selection.deep_view(),
        }
    }
}

#[repr(i16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, StructuralEq)]
#[verifier::ext_equal]
pub enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

pub type ColorSpec = Color;
impl DeepView for Color {
    type V = Self;
    open spec fn deep_view(&self) -> Self::V { *self }
}
#[cfg(not(verus_keep_ghost))]
unsafe impl Structural for Color {}

pub type Identifier<'a> = vest_lib2::asn1::ObjectIdentifier<'a>;
pub type IdentifierSpec = vest_lib2::asn1::ObjectIdentifierSpec;

pub type Measurement<'a> = vest_lib2::asn1::Real<'a>;
pub type MeasurementSpec = vest_lib2::asn1::RealSpec;

pub type OpenValue<'a> = vest_lib2::asn1::Any<'a>;
pub type OpenValueSpec = vest_lib2::asn1::AnySpec;

/// Value type for ASN.1 `Metadata`.
pub struct Metadata<'a> {
    pub color: Color,
    pub identifier: Identifier<'a>,
    pub measurement: Measurement<'a>,
    pub open: OpenValue<'a>,
}

#[verifier::ext_equal]
pub struct MetadataSpec {
    pub color: ColorSpec,
    pub identifier: IdentifierSpec,
    pub measurement: MeasurementSpec,
    pub open: OpenValueSpec,
}

impl<'a> DeepView for Metadata<'a> {
    type V = MetadataSpec;
    open spec fn deep_view(&self) -> Self::V {
        MetadataSpec {
            color: self.color.deep_view(),
            identifier: self.identifier.deep_view(),
            measurement: self.measurement.deep_view(),
            open: self.open.deep_view(),
        }
    }
}

/// Value type for ASN.1 `InlineRecord-nested`.
pub struct InlineRecordNested<'a> {
    pub payload: &'a [u8],
}

#[verifier::ext_equal]
pub struct InlineRecordNestedSpec {
    pub payload: Seq<u8>,
}

impl<'a> DeepView for InlineRecordNested<'a> {
    type V = InlineRecordNestedSpec;
    open spec fn deep_view(&self) -> Self::V {
        InlineRecordNestedSpec {
            payload: self.payload.deep_view(),
        }
    }
}

/// Value type for ASN.1 `InlineRecord-selected`.
pub enum InlineRecordSelected<'a> {
    Flag(bool),
    Identifier(vest_lib2::asn1::ObjectIdentifier<'a>),
}

#[verifier::ext_equal]
pub enum InlineRecordSelectedSpec {
    Flag(bool),
    Identifier(vest_lib2::asn1::ObjectIdentifierSpec),
}

impl<'a> DeepView for InlineRecordSelected<'a> {
    type V = InlineRecordSelectedSpec;
    open spec fn deep_view(&self) -> Self::V {
        match self {
            InlineRecordSelected::Flag(value) => InlineRecordSelectedSpec::Flag(value.deep_view()),
            InlineRecordSelected::Identifier(value) => InlineRecordSelectedSpec::Identifier(value.deep_view()),
        }
    }
}

/// Value type for ASN.1 `InlineRecord`.
pub struct InlineRecord<'a> {
    pub nested: InlineRecordNested<'a>,
    pub selected: InlineRecordSelected<'a>,
}

#[verifier::ext_equal]
pub struct InlineRecordSpec {
    pub nested: InlineRecordNestedSpec,
    pub selected: InlineRecordSelectedSpec,
}

impl<'a> DeepView for InlineRecord<'a> {
    type V = InlineRecordSpec;
    open spec fn deep_view(&self) -> Self::V {
        InlineRecordSpec {
            nested: self.nested.deep_view(),
            selected: self.selected.deep_view(),
        }
    }
}

#[derive(Clone, Copy)]
pub struct HeaderForward;
#[derive(Clone, Copy)]
pub struct HeaderReverse;

impl SpecMap for HeaderForward {
    type Input = (FlagSpec, (CountSpec, ()));
    type Output = HeaderSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (flag, (count, _end)) = input;
        HeaderSpec {
            flag,
            count,
        }
    }
}

impl SpecMap for HeaderReverse {
    type Input = HeaderSpec;
    type Output = (FlagSpec, (CountSpec, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.flag, (value.count, ()))
    }
}

impl<'a> Map<(Flag, (Count<'a>, ()))> for HeaderForward {
    type O = Header<'a>;
    fn map(&self, input: (Flag, (Count<'a>, ()))) -> (value: Self::O) {
        let (flag, (count, _end)) = input;
        Header {
            flag,
            count,
        }
    }
}

impl<'a, 'x> Map<&'x Header<'a>> for HeaderReverse {
    type O = (&'x Flag, (&'x Count<'a>, ()));
    fn map(&self, value: &'x Header<'a>) -> (output: Self::O) {
        (&value.flag, (&value.count, ()))
    }
}

#[derive(Clone, Copy)]
pub struct EnvelopeForward;
#[derive(Clone, Copy)]
pub struct EnvelopeReverse;

impl SpecMap for EnvelopeForward {
    type Input = (HeaderSpec, (Option<PayloadSpec>, ()));
    type Output = EnvelopeSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (header, (payload, _end)) = input;
        EnvelopeSpec {
            header,
            payload,
        }
    }
}

impl SpecMap for EnvelopeReverse {
    type Input = EnvelopeSpec;
    type Output = (HeaderSpec, (Option<PayloadSpec>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.header, (value.payload, ()))
    }
}

impl<'a> Map<(Header<'a>, (Option<Payload<'a>>, ()))> for EnvelopeForward {
    type O = Envelope<'a>;
    fn map(&self, input: (Header<'a>, (Option<Payload<'a>>, ()))) -> (value: Self::O) {
        let (header, (payload, _end)) = input;
        Envelope {
            header,
            payload,
        }
    }
}

impl<'a, 'x> Map<&'x Envelope<'a>> for EnvelopeReverse {
    type O = (&'x Header<'a>, (Option<&'x Payload<'a>>, ()));
    fn map(&self, value: &'x Envelope<'a>) -> (output: Self::O) {
        (&value.header, (value.payload.as_ref(), ()))
    }
}

#[derive(Clone, Copy)]
pub struct FeaturesForward;
#[derive(Clone, Copy)]
pub struct FeaturesReverse;

impl SpecMap for FeaturesForward {
    type Input = (FlagSpec, (bool, ()));
    type Output = FeaturesSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (enabled, (visible, _end)) = input;
        FeaturesSpec {
            enabled,
            visible,
        }
    }
}

impl SpecMap for FeaturesReverse {
    type Input = FeaturesSpec;
    type Output = (FlagSpec, (bool, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.enabled, (value.visible, ()))
    }
}

impl Map<(Flag, (bool, ()))> for FeaturesForward {
    type O = Features;
    fn map(&self, input: (Flag, (bool, ()))) -> (value: Self::O) {
        let (enabled, (visible, _end)) = input;
        Features {
            enabled,
            visible,
        }
    }
}

impl<'x> Map<&'x Features> for FeaturesReverse {
    type O = (Flag, (bool, ()));
    fn map(&self, value: &'x Features) -> (output: Self::O) {
        (value.enabled, (value.visible, ()))
    }
}

#[derive(Clone, Copy)]
pub struct SelectionForward;
#[derive(Clone, Copy)]
pub struct SelectionReverse;

impl SpecMap for SelectionForward {
    type Input = Sum<FlagSpec, PayloadSpec>;
    type Output = SelectionSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        match input {
            Sum::Inl(value) => SelectionSpec::Flag(value),
            Sum::Inr(value) => SelectionSpec::Payload(value),
        }
    }
}

impl SpecMap for SelectionReverse {
    type Input = SelectionSpec;
    type Output = Sum<FlagSpec, PayloadSpec>;
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        match value {
            SelectionSpec::Flag(value) => Sum::Inl(value),
            SelectionSpec::Payload(value) => Sum::Inr(value),
        }
    }
}

impl<'a> Map<Sum<Flag, Payload<'a>>> for SelectionForward {
    type O = Selection<'a>;
    fn map(&self, input: Sum<Flag, Payload<'a>>) -> (value: Self::O) {
        match input {
            Sum::Inl(value) => Selection::Flag(value),
            Sum::Inr(value) => Selection::Payload(value),
        }
    }
}

impl<'a, 'x> Map<&'x Selection<'a>> for SelectionReverse {
    type O = Sum<&'x Flag, &'x Payload<'a>>;
    fn map(&self, value: &'x Selection<'a>) -> (output: Self::O) {
        match value {
            Selection::Flag(value) => Sum::Inl(value),
            Selection::Payload(value) => Sum::Inr(value),
        }
    }
}

#[derive(Clone, Copy)]
pub struct ChoiceEnvelopeForward;
#[derive(Clone, Copy)]
pub struct ChoiceEnvelopeReverse;

impl SpecMap for ChoiceEnvelopeForward {
    type Input = (Option<SelectionSpec>, ());
    type Output = ChoiceEnvelopeSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (selection, _end) = input;
        ChoiceEnvelopeSpec {
            selection,
        }
    }
}

impl SpecMap for ChoiceEnvelopeReverse {
    type Input = ChoiceEnvelopeSpec;
    type Output = (Option<SelectionSpec>, ());
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.selection, ())
    }
}

impl<'a> Map<(Option<Selection<'a>>, ())> for ChoiceEnvelopeForward {
    type O = ChoiceEnvelope<'a>;
    fn map(&self, input: (Option<Selection<'a>>, ())) -> (value: Self::O) {
        let (selection, _end) = input;
        ChoiceEnvelope {
            selection,
        }
    }
}

impl<'a, 'x> Map<&'x ChoiceEnvelope<'a>> for ChoiceEnvelopeReverse {
    type O = (Option<&'x Selection<'a>>, ());
    fn map(&self, value: &'x ChoiceEnvelope<'a>) -> (output: Self::O) {
        (value.selection.as_ref(), ())
    }
}

#[derive(Clone, Copy)]
pub struct ColorPredicate;
impl SpecPred<i16> for ColorPredicate {
    open spec fn apply(&self, value: i16) -> bool {
        value == 0i16 || value == 1i16 || value == 2i16
    }
}
impl Pred<i16> for ColorPredicate {
    fn test(&self, value: &i16) -> (ok: bool) {
        *value == 0i16 || *value == 1i16 || *value == 2i16
    }
}

#[derive(Clone, Copy)]
pub struct ColorForward;
#[derive(Clone, Copy)]
pub struct ColorReverse;

impl SpecMap for ColorForward {
    type Input = i16;
    type Output = Color;
    open spec fn spec_map(&self, value: i16) -> Self::Output {
        match value {
            0i16 => Color::Red,
            1i16 => Color::Green,
            2i16 => Color::Blue,
            _ => Color::Red,
        }
    }
}

impl SpecMap for ColorReverse {
    type Input = Color;
    type Output = i16;
    open spec fn spec_map(&self, value: Self::Input) -> i16 {
        match value {
            Color::Red => 0i16,
            Color::Green => 1i16,
            Color::Blue => 2i16,
        }
    }
}

impl Map<i16> for ColorForward {
    type O = Color;
    fn map(&self, value: i16) -> (output: Self::O) {
        match value {
            0i16 => Color::Red,
            1i16 => Color::Green,
            2i16 => Color::Blue,
            _ => Color::Red,
        }
    }
}

impl<'a> Map<&'a Color> for ColorReverse {
    type O = i16;
    fn map(&self, value: &'a Color) -> (output: i16) {
        match value {
            Color::Red => 0i16,
            Color::Green => 1i16,
            Color::Blue => 2i16,
        }
    }
}

#[derive(Clone, Copy)]
pub struct MetadataForward;
#[derive(Clone, Copy)]
pub struct MetadataReverse;

impl SpecMap for MetadataForward {
    type Input = (ColorSpec, (IdentifierSpec, (MeasurementSpec, (OpenValueSpec, ()))));
    type Output = MetadataSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (color, (identifier, (measurement, (open, _end)))) = input;
        MetadataSpec {
            color,
            identifier,
            measurement,
            open,
        }
    }
}

impl SpecMap for MetadataReverse {
    type Input = MetadataSpec;
    type Output = (ColorSpec, (IdentifierSpec, (MeasurementSpec, (OpenValueSpec, ()))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.color, (value.identifier, (value.measurement, (value.open, ()))))
    }
}

impl<'a> Map<(Color, (Identifier<'a>, (Measurement<'a>, (OpenValue<'a>, ()))))> for MetadataForward {
    type O = Metadata<'a>;
    fn map(&self, input: (Color, (Identifier<'a>, (Measurement<'a>, (OpenValue<'a>, ()))))) -> (value: Self::O) {
        let (color, (identifier, (measurement, (open, _end)))) = input;
        Metadata {
            color,
            identifier,
            measurement,
            open,
        }
    }
}

impl<'a, 'x> Map<&'x Metadata<'a>> for MetadataReverse {
    type O = (Color, (&'x Identifier<'a>, (&'x Measurement<'a>, (&'x OpenValue<'a>, ()))));
    fn map(&self, value: &'x Metadata<'a>) -> (output: Self::O) {
        (value.color, (&value.identifier, (&value.measurement, (&value.open, ()))))
    }
}

#[derive(Clone, Copy)]
pub struct InlineRecordNestedForward;
#[derive(Clone, Copy)]
pub struct InlineRecordNestedReverse;

impl SpecMap for InlineRecordNestedForward {
    type Input = (Seq<u8>, ());
    type Output = InlineRecordNestedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (payload, _end) = input;
        InlineRecordNestedSpec {
            payload,
        }
    }
}

impl SpecMap for InlineRecordNestedReverse {
    type Input = InlineRecordNestedSpec;
    type Output = (Seq<u8>, ());
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.payload, ())
    }
}

impl<'a> Map<(&'a [u8], ())> for InlineRecordNestedForward {
    type O = InlineRecordNested<'a>;
    fn map(&self, input: (&'a [u8], ())) -> (value: Self::O) {
        let (payload, _end) = input;
        InlineRecordNested {
            payload,
        }
    }
}

impl<'a, 'x> Map<&'x InlineRecordNested<'a>> for InlineRecordNestedReverse {
    type O = (&'x &'a [u8], ());
    fn map(&self, value: &'x InlineRecordNested<'a>) -> (output: Self::O) {
        (&value.payload, ())
    }
}

#[derive(Clone, Copy)]
pub struct InlineRecordSelectedForward;
#[derive(Clone, Copy)]
pub struct InlineRecordSelectedReverse;

impl SpecMap for InlineRecordSelectedForward {
    type Input = Sum<bool, vest_lib2::asn1::ObjectIdentifierSpec>;
    type Output = InlineRecordSelectedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        match input {
            Sum::Inl(value) => InlineRecordSelectedSpec::Flag(value),
            Sum::Inr(value) => InlineRecordSelectedSpec::Identifier(value),
        }
    }
}

impl SpecMap for InlineRecordSelectedReverse {
    type Input = InlineRecordSelectedSpec;
    type Output = Sum<bool, vest_lib2::asn1::ObjectIdentifierSpec>;
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        match value {
            InlineRecordSelectedSpec::Flag(value) => Sum::Inl(value),
            InlineRecordSelectedSpec::Identifier(value) => Sum::Inr(value),
        }
    }
}

impl<'a> Map<Sum<bool, vest_lib2::asn1::ObjectIdentifier<'a>>> for InlineRecordSelectedForward {
    type O = InlineRecordSelected<'a>;
    fn map(&self, input: Sum<bool, vest_lib2::asn1::ObjectIdentifier<'a>>) -> (value: Self::O) {
        match input {
            Sum::Inl(value) => InlineRecordSelected::Flag(value),
            Sum::Inr(value) => InlineRecordSelected::Identifier(value),
        }
    }
}

impl<'a, 'x> Map<&'x InlineRecordSelected<'a>> for InlineRecordSelectedReverse {
    type O = Sum<&'x bool, &'x vest_lib2::asn1::ObjectIdentifier<'a>>;
    fn map(&self, value: &'x InlineRecordSelected<'a>) -> (output: Self::O) {
        match value {
            InlineRecordSelected::Flag(value) => Sum::Inl(value),
            InlineRecordSelected::Identifier(value) => Sum::Inr(value),
        }
    }
}

#[derive(Clone, Copy)]
pub struct InlineRecordForward;
#[derive(Clone, Copy)]
pub struct InlineRecordReverse;

impl SpecMap for InlineRecordForward {
    type Input = (InlineRecordNestedSpec, (InlineRecordSelectedSpec, ()));
    type Output = InlineRecordSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (nested, (selected, _end)) = input;
        InlineRecordSpec {
            nested,
            selected,
        }
    }
}

impl SpecMap for InlineRecordReverse {
    type Input = InlineRecordSpec;
    type Output = (InlineRecordNestedSpec, (InlineRecordSelectedSpec, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.nested, (value.selected, ()))
    }
}

impl<'a> Map<(InlineRecordNested<'a>, (InlineRecordSelected<'a>, ()))> for InlineRecordForward {
    type O = InlineRecord<'a>;
    fn map(&self, input: (InlineRecordNested<'a>, (InlineRecordSelected<'a>, ()))) -> (value: Self::O) {
        let (nested, (selected, _end)) = input;
        InlineRecord {
            nested,
            selected,
        }
    }
}

impl<'a, 'x> Map<&'x InlineRecord<'a>> for InlineRecordReverse {
    type O = (&'x InlineRecordNested<'a>, (&'x InlineRecordSelected<'a>, ()));
    fn map(&self, value: &'x InlineRecord<'a>) -> (output: Self::O) {
        (&value.nested, (&value.selected, ()))
    }
}

/// DER format for ASN.1 `Flag`.
pub type FlagFmt = ASN1BoolFmt<DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn FLAG_FMT() -> FlagFmt
    returns
        (BOOLEAN),
{
    BOOLEAN
}

/// DER format for ASN.1 `Count`.
pub type CountFmt = ASN1IntegerFmt<DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn COUNT_FMT() -> CountFmt
    returns
        (INTEGER),
{
    INTEGER
}

/// DER format for ASN.1 `Payload`.
pub type PayloadFmt = ASN1Fmt<Refined<OctetStringFmt, Size<true, 2, true, 4>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn PAYLOAD_FMT() -> PayloadFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::OCTET_STRING, Refined(OctetStringFmt, Size::<true, 2, true, 4>))),
{
    ASN1Fmt::<_, DER>(TagFmt::OCTET_STRING, Refined(OctetStringFmt, Size::<true, 2, true, 4>))
}

/// DER format for ASN.1 `Header`.
pub type HeaderFmt = ASN1Fmt<Mapped<Pair<Ref<FlagFmt>, Pair<Ref<CountFmt>, Eof>>, BiMap<HeaderForward, HeaderReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn HEADER_FMT() -> HeaderFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(FLAG_FMT()), REQUIRED(Ref(COUNT_FMT()), Eof)), mapper: BiMap(HeaderForward, HeaderReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(FLAG_FMT()), REQUIRED(Ref(COUNT_FMT()), Eof)), mapper: BiMap(HeaderForward, HeaderReverse) })
}

/// DER format for ASN.1 `Envelope`.
pub type EnvelopeFmt = ASN1Fmt<Mapped<Pair<Ref<HeaderFmt>, Optional<Ref<PayloadFmt>, Eof>>, BiMap<EnvelopeForward, EnvelopeReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ENVELOPE_FMT() -> EnvelopeFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(HEADER_FMT()), OPTIONAL(Ref(IMPLICIT(0u64, PAYLOAD_FMT())), Eof)), mapper: BiMap(EnvelopeForward, EnvelopeReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(HEADER_FMT()), OPTIONAL(Ref(IMPLICIT(0u64, PAYLOAD_FMT())), Eof)), mapper: BiMap(EnvelopeForward, EnvelopeReverse) })
}

/// DER format for ASN.1 `Envelopes`.
pub type EnvelopesFmt = ASN1Fmt<RepeatTillEnd<EnvelopeFmt>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ENVELOPES_FMT() -> EnvelopesFmt
    returns
        (SEQUENCE_OF(ENVELOPE_FMT())),
{
    SEQUENCE_OF(ENVELOPE_FMT())
}

/// DER format for ASN.1 `Features`.
pub type FeaturesFmt = ASN1Fmt<Mapped<DefaultedFmt<FlagFmt, bool, DefaultedFmt<ASN1BoolFmt<DER>, bool, Eof, DER>, DER>, BiMap<FeaturesForward, FeaturesReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn FEATURES_FMT() -> FeaturesFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: DEFAULT(IMPLICIT(0u64, FLAG_FMT()), true, DEFAULT(IMPLICIT(1u64, BOOLEAN), false, Eof)), mapper: BiMap(FeaturesForward, FeaturesReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: DEFAULT(IMPLICIT(0u64, FLAG_FMT()), true, DEFAULT(IMPLICIT(1u64, BOOLEAN), false, Eof)), mapper: BiMap(FeaturesForward, FeaturesReverse) })
}

/// DER format for ASN.1 `Selection`.
pub type SelectionFmt = Mapped<Choice<Ref<FlagFmt>, Ref<ASN1Fmt<PayloadFmt, DER>>>, BiMap<SelectionForward, SelectionReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn SELECTION_FMT() -> SelectionFmt
    returns
        (Mapped { inner: CHOICE(Ref(IMPLICIT(1u64, FLAG_FMT())), Ref(EXPLICIT(2u64, PAYLOAD_FMT()))), mapper: BiMap(SelectionForward, SelectionReverse) }),
{
    Mapped { inner: CHOICE(Ref(IMPLICIT(1u64, FLAG_FMT())), Ref(EXPLICIT(2u64, PAYLOAD_FMT()))), mapper: BiMap(SelectionForward, SelectionReverse) }
}

/// DER format for ASN.1 `ChoiceEnvelope`.
pub type ChoiceEnvelopeFmt = ASN1Fmt<Mapped<Optional<Ref<ASN1Fmt<SelectionFmt, DER>>, Eof>, BiMap<ChoiceEnvelopeForward, ChoiceEnvelopeReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn CHOICE_ENVELOPE_FMT() -> ChoiceEnvelopeFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: OPTIONAL(Ref(EXPLICIT(3u64, SELECTION_FMT())), Eof), mapper: BiMap(ChoiceEnvelopeForward, ChoiceEnvelopeReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: OPTIONAL(Ref(EXPLICIT(3u64, SELECTION_FMT())), Eof), mapper: BiMap(ChoiceEnvelopeForward, ChoiceEnvelopeReverse) })
}

/// DER format for ASN.1 `Color`.
pub type ColorFmt = ASN1Fmt<Mapped<Refined<Integer16Fmt, ColorPredicate>, BiMap<ColorForward, ColorReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn COLOR_FMT() -> ColorFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::ENUMERATED, Mapped { inner: Refined(Integer16Fmt, ColorPredicate), mapper: BiMap(ColorForward, ColorReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::ENUMERATED, Mapped { inner: Refined(Integer16Fmt, ColorPredicate), mapper: BiMap(ColorForward, ColorReverse) })
}

/// DER format for ASN.1 `Identifier`.
pub type IdentifierFmt = ASN1ObjectIdentifierFmt<DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn IDENTIFIER_FMT() -> IdentifierFmt
    returns
        (OBJECT_IDENTIFIER),
{
    OBJECT_IDENTIFIER
}

/// DER format for ASN.1 `Measurement`.
pub type MeasurementFmt = ASN1RealFmt<DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn MEASUREMENT_FMT() -> MeasurementFmt
    returns
        (REAL),
{
    REAL
}

/// DER format for ASN.1 `OpenValue`.
pub type OpenValueFmt = ASN1AnyFmt<DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn OPEN_VALUE_FMT() -> OpenValueFmt
    returns
        (ANY),
{
    ANY
}

/// DER format for ASN.1 `Metadata`.
pub type MetadataFmt = ASN1Fmt<Mapped<DefaultedFmt<ColorFmt, Color, Pair<Ref<IdentifierFmt>, Pair<Ref<MeasurementFmt>, Pair<Ref<ASN1Fmt<OpenValueFmt, DER>>, Eof>>>, DER>, BiMap<MetadataForward, MetadataReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn METADATA_FMT() -> MetadataFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: DEFAULT(IMPLICIT(0u64, COLOR_FMT()), Color::Green, REQUIRED(Ref(IDENTIFIER_FMT()), REQUIRED(Ref(MEASUREMENT_FMT()), REQUIRED(Ref(EXPLICIT(1u64, OPEN_VALUE_FMT())), Eof)))), mapper: BiMap(MetadataForward, MetadataReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: DEFAULT(IMPLICIT(0u64, COLOR_FMT()), Color::Green, REQUIRED(Ref(IDENTIFIER_FMT()), REQUIRED(Ref(MEASUREMENT_FMT()), REQUIRED(Ref(EXPLICIT(1u64, OPEN_VALUE_FMT())), Eof)))), mapper: BiMap(MetadataForward, MetadataReverse) })
}

/// DER format for ASN.1 `InlineRecord-nested`.
pub type InlineRecordNestedFmt = ASN1Fmt<Mapped<Pair<Ref<ASN1OctetStringFmt<DER>>, Eof>, BiMap<InlineRecordNestedForward, InlineRecordNestedReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn INLINE_RECORD_NESTED_FMT() -> InlineRecordNestedFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(OCTET_STRING), Eof), mapper: BiMap(InlineRecordNestedForward, InlineRecordNestedReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(OCTET_STRING), Eof), mapper: BiMap(InlineRecordNestedForward, InlineRecordNestedReverse) })
}

/// DER format for ASN.1 `InlineRecord-selected`.
pub type InlineRecordSelectedFmt = Mapped<Choice<Ref<ASN1BoolFmt<DER>>, Ref<ASN1ObjectIdentifierFmt<DER>>>, BiMap<InlineRecordSelectedForward, InlineRecordSelectedReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn INLINE_RECORD_SELECTED_FMT() -> InlineRecordSelectedFmt
    returns
        (Mapped { inner: CHOICE(Ref(IMPLICIT(2u64, BOOLEAN)), Ref(IMPLICIT(3u64, OBJECT_IDENTIFIER))), mapper: BiMap(InlineRecordSelectedForward, InlineRecordSelectedReverse) }),
{
    Mapped { inner: CHOICE(Ref(IMPLICIT(2u64, BOOLEAN)), Ref(IMPLICIT(3u64, OBJECT_IDENTIFIER))), mapper: BiMap(InlineRecordSelectedForward, InlineRecordSelectedReverse) }
}

/// DER format for ASN.1 `InlineRecord`.
pub type InlineRecordFmt = ASN1Fmt<Mapped<Pair<Ref<InlineRecordNestedFmt>, Pair<Ref<InlineRecordSelectedFmt>, Eof>>, BiMap<InlineRecordForward, InlineRecordReverse>>, DER>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn INLINE_RECORD_FMT() -> InlineRecordFmt
    returns
        (ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(INLINE_RECORD_NESTED_FMT()), REQUIRED(Ref(INLINE_RECORD_SELECTED_FMT()), Eof)), mapper: BiMap(InlineRecordForward, InlineRecordReverse) })),
{
    ASN1Fmt::<_, DER>(TagFmt::SEQUENCE, Mapped { inner: REQUIRED(Ref(INLINE_RECORD_NESTED_FMT()), REQUIRED(Ref(INLINE_RECORD_SELECTED_FMT()), Eof)), mapper: BiMap(InlineRecordForward, InlineRecordReverse) })
}

proof fn vestasn1_generated_formats_are_valid() {
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::modifiers::{lemma_disjoint_asn1_tags, lemma_disjoint_defaulted};
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use {lemma_disjoint_asn1_tags, lemma_disjoint_defaulted};
    assert(FLAG_FMT().safe_inv());
    assert(FLAG_FMT().sound_inv());
    assert(FLAG_FMT().unambiguous());
    assert(COUNT_FMT().safe_inv());
    assert(COUNT_FMT().sound_inv());
    assert(COUNT_FMT().unambiguous());
    assert(PAYLOAD_FMT().safe_inv());
    assert(PAYLOAD_FMT().sound_inv());
    assert(PAYLOAD_FMT().unambiguous());
    assert(HEADER_FMT().safe_inv());
    assert(HEADER_FMT().sound_inv());
    assert((HEADER_FMT().1.inner).unambiguous());
    assert(HEADER_FMT().unambiguous());
    assert(ENVELOPE_FMT().safe_inv());
    assert(ENVELOPE_FMT().sound_inv());
    assert(disjoint_domains(((ENVELOPE_FMT().1.inner).1).0, ((ENVELOPE_FMT().1.inner).1).1));
    assert((ENVELOPE_FMT().1.inner).unambiguous());
    assert(ENVELOPE_FMT().unambiguous());
    assert(ENVELOPES_FMT().safe_inv());
    assert(ENVELOPES_FMT().sound_inv());
    assert(ENVELOPES_FMT().unambiguous());
    assert(FEATURES_FMT().safe_inv());
    assert(FEATURES_FMT().sound_inv());
    lemma_disjoint_asn1_tags((FEATURES_FMT().1.inner).0, ((FEATURES_FMT().1.inner).2).0);
    assert(disjoint_domains((FEATURES_FMT().1.inner).0, (FEATURES_FMT().1.inner).2));
    assert(disjoint_domains(((FEATURES_FMT().1.inner).2).0, ((FEATURES_FMT().1.inner).2).2));
    assert((FEATURES_FMT().1.inner).unambiguous());
    assert(FEATURES_FMT().unambiguous());
    assert(SELECTION_FMT().safe_inv());
    assert(SELECTION_FMT().sound_inv());
    lemma_disjoint_asn1_tags(((SELECTION_FMT().inner).0).0, ((SELECTION_FMT().inner).1).0);
    vest_lib2::combinators::disjoint::lemma_disjoint_refs((SELECTION_FMT().inner).0, (SELECTION_FMT().inner).1);
    assert((SELECTION_FMT().inner).unambiguous());
    assert(SELECTION_FMT().unambiguous());
    assert(CHOICE_ENVELOPE_FMT().safe_inv());
    assert(CHOICE_ENVELOPE_FMT().sound_inv());
    assert(disjoint_domains((CHOICE_ENVELOPE_FMT().1.inner).0, (CHOICE_ENVELOPE_FMT().1.inner).1));
    assert((CHOICE_ENVELOPE_FMT().1.inner).unambiguous());
    assert(CHOICE_ENVELOPE_FMT().unambiguous());
    assert(COLOR_FMT().safe_inv());
    assert(COLOR_FMT().sound_inv());
    assert(COLOR_FMT().unambiguous());
    assert(IDENTIFIER_FMT().safe_inv());
    assert(IDENTIFIER_FMT().sound_inv());
    assert(IDENTIFIER_FMT().unambiguous());
    assert(MEASUREMENT_FMT().safe_inv());
    assert(MEASUREMENT_FMT().sound_inv());
    assert(MEASUREMENT_FMT().unambiguous());
    assert(OPEN_VALUE_FMT().safe_inv());
    assert(OPEN_VALUE_FMT().sound_inv());
    assert(OPEN_VALUE_FMT().unambiguous());
    assert(METADATA_FMT().safe_inv());
    assert(METADATA_FMT().sound_inv());
    lemma_disjoint_asn1_tags((METADATA_FMT().1.inner).0, (((METADATA_FMT().1.inner).2).0).0);
    vest_lib2::combinators::disjoint::lemma_disjoint_ref_right((METADATA_FMT().1.inner).0, ((METADATA_FMT().1.inner).2).0);
    assert(disjoint_domains((METADATA_FMT().1.inner).0, (METADATA_FMT().1.inner).2));
    assert((METADATA_FMT().1.inner).unambiguous());
    assert(METADATA_FMT().unambiguous());
    assert(INLINE_RECORD_NESTED_FMT().safe_inv());
    assert(INLINE_RECORD_NESTED_FMT().sound_inv());
    assert((INLINE_RECORD_NESTED_FMT().1.inner).unambiguous());
    assert(INLINE_RECORD_NESTED_FMT().unambiguous());
    assert(INLINE_RECORD_SELECTED_FMT().safe_inv());
    assert(INLINE_RECORD_SELECTED_FMT().sound_inv());
    lemma_disjoint_asn1_tags(((INLINE_RECORD_SELECTED_FMT().inner).0).0, ((INLINE_RECORD_SELECTED_FMT().inner).1).0);
    vest_lib2::combinators::disjoint::lemma_disjoint_refs((INLINE_RECORD_SELECTED_FMT().inner).0, (INLINE_RECORD_SELECTED_FMT().inner).1);
    assert((INLINE_RECORD_SELECTED_FMT().inner).unambiguous());
    assert(INLINE_RECORD_SELECTED_FMT().unambiguous());
    assert(INLINE_RECORD_FMT().safe_inv());
    assert(INLINE_RECORD_FMT().sound_inv());
    assert((INLINE_RECORD_FMT().1.inner).unambiguous());
    assert(INLINE_RECORD_FMT().unambiguous());
}

} // verus!

pub const BASE_OID: vest_lib2::asn1::ObjectIdentifier<'static> = vest_lib2::asn1::ObjectIdentifier::from_static_der_contents_unchecked(&[0x2au8, 0x86u8, 0x48u8, 0x86u8, 0xf7u8, 0x0du8]);
pub const CHILD_OID: Identifier<'static> = vest_lib2::asn1::ObjectIdentifier::from_static_der_contents_unchecked(&[0x2au8, 0x86u8, 0x48u8, 0x86u8, 0xf7u8, 0x0du8, 0x01u8]);
pub const FEATURE_ENABLED: Flag = true;
pub const ANSWER: Count<'static> = vest_lib2::asn1::Integer::from_i64(42i64);
pub const DEFAULT_COLOR: Color = Color::Green;
