// @generated by vestasn1 from ASN.1 module `MixedFixture`.
// Generated formats parse and serialize a schema-selected mixture of BER and DER.
#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use vest_lib2::asn1::*;
use vest_lib2::asn1::der_ord::{DerOrd, DerState};
use vest_lib2::asn1::disjoint::HasAsn1Start;
use vest_lib2::asn1::tag::tag_num_from_uint;
use vest_lib2::asn1::modifiers::{implicitly_tagged as Implicit, ImplicitFmt, CHOICE, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, OPTIONAL, REQUIRED};
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::combinators::Eof;
use Sum::Inl as L;
use Sum::Inr as R;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::exec::output::OutputBuf;
use vest_lib2::core::exec::parser::{PResult, Parser};
use vest_lib2::core::exec::serializer::{ByteLen, PreSerializeError, Prepare, Serializer};
use vest_lib2::core::proof::*;
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Version = i8;
pub type VersionSpec = i8;

pub type VersionDer = i8;
pub type VersionDerSpec = i8;

/// Value type for ASN.1 `Shared`.
pub struct Shared {
    pub version: Version,
    pub payload: Vec<u8>,
}

#[verifier::ext_equal]
pub struct SharedSpec {
    pub version: VersionSpec,
    pub payload: Seq<u8>,
}

impl DeepView for Shared {
    type V = SharedSpec;
    open spec fn deep_view(&self) -> Self::V {
        SharedSpec {
            version: self.version.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Shared-der`.
pub struct SharedDer<'a> {
    pub version: VersionDer,
    pub payload: &'a [u8],
}

#[verifier::ext_equal]
pub struct SharedDerSpec {
    pub version: VersionDerSpec,
    pub payload: Seq<u8>,
}

impl<'a> DeepView for SharedDer<'a> {
    type V = SharedDerSpec;
    open spec fn deep_view(&self) -> Self::V {
        SharedDerSpec {
            version: self.version.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

pub type Canonical<'a> = Vec<SharedDer<'a>>;
pub type CanonicalSpec = Seq<SharedDerSpec>;

/// Value type for ASN.1 `Ordered`.
pub struct Ordered<'a> {
    pub first: bool,
    pub second: Option<vest_lib2::asn1::Integer<'a>>,
}

#[verifier::ext_equal]
pub struct OrderedSpec {
    pub first: bool,
    pub second: Option<int>,
}

impl<'a> DeepView for Ordered<'a> {
    type V = OrderedSpec;
    open spec fn deep_view(&self) -> Self::V {
        OrderedSpec {
            first: self.first.deep_view(),
            second: self.second.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Outer`.
pub struct Outer<'a> {
    pub shared: Shared,
    pub canonical: Canonical<'a>,
    pub ordered: Ordered<'a>,
    pub trailing: Option<vest_lib2::asn1::AnyOwned>,
}

#[verifier::ext_equal]
pub struct OuterSpec {
    pub shared: SharedSpec,
    pub canonical: CanonicalSpec,
    pub ordered: OrderedSpec,
    pub trailing: Option<vest_lib2::asn1::AnySpec>,
}

impl<'a> DeepView for Outer<'a> {
    type V = OuterSpec;
    open spec fn deep_view(&self) -> Self::V {
        OuterSpec {
            shared: self.shared.deep_view(),
            canonical: self.canonical.deep_view(),
            ordered: self.ordered.deep_view(),
            trailing: self.trailing.deep_view(),
        }
    }
}

pub type NumericLabel = vest_lib2::asn1::NumericStringOwned;
pub type NumericLabelSpec = vest_lib2::asn1::NumericStringSpec;

pub type UniversalLabel = vest_lib2::asn1::UniversalString;
pub type UniversalLabelSpec = vest_lib2::asn1::UniversalStringSpec;

#[derive(Clone, Copy)]
pub struct SharedForward;
#[derive(Clone, Copy)]
pub struct SharedReverse;

impl SpecMap for SharedForward {
    type Input = (VersionSpec, (Seq<u8>, ()));
    type Output = SharedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (version, (payload, _end)) = input;
        SharedSpec {
            version,
            payload,
        }
    }
}

impl SpecMap for SharedReverse {
    type Input = SharedSpec;
    type Output = (VersionSpec, (Seq<u8>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.version, (value.payload, ()))
    }
}

impl Map<(Version, (Vec<u8>, ()))> for SharedForward {
    type O = Shared;
    fn map(&self, input: (Version, (Vec<u8>, ()))) -> (value: Self::O) {
        let (version, (payload, _end)) = input;
        Shared {
            version,
            payload,
        }
    }
}

impl<'x> Map<&'x Shared> for SharedReverse {
    type O = (Version, (&'x Vec<u8>, ()));
    fn map(&self, value: &'x Shared) -> (output: Self::O) {
        (value.version, (&value.payload, ()))
    }
}

#[derive(Clone, Copy)]
pub struct SharedDerForward;
#[derive(Clone, Copy)]
pub struct SharedDerReverse;

impl SpecMap for SharedDerForward {
    type Input = (VersionDerSpec, (Seq<u8>, ()));
    type Output = SharedDerSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (version, (payload, _end)) = input;
        SharedDerSpec {
            version,
            payload,
        }
    }
}

impl SpecMap for SharedDerReverse {
    type Input = SharedDerSpec;
    type Output = (VersionDerSpec, (Seq<u8>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.version, (value.payload, ()))
    }
}

impl<'a> Map<(VersionDer, (&'a [u8], ()))> for SharedDerForward {
    type O = SharedDer<'a>;
    fn map(&self, input: (VersionDer, (&'a [u8], ()))) -> (value: Self::O) {
        let (version, (payload, _end)) = input;
        SharedDer {
            version,
            payload,
        }
    }
}

impl<'a, 'x> Map<&'x SharedDer<'a>> for SharedDerReverse {
    type O = (VersionDer, (&'x &'a [u8], ()));
    fn map(&self, value: &'x SharedDer<'a>) -> (output: Self::O) {
        (value.version, (&value.payload, ()))
    }
}

#[derive(Clone, Copy)]
pub struct OrderedForward;
#[derive(Clone, Copy)]
pub struct OrderedReverse;

impl SpecMap for OrderedForward {
    type Input = (bool, (Option<int>, ()));
    type Output = OrderedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (first, (second, _end)) = input;
        OrderedSpec {
            first,
            second,
        }
    }
}

impl SpecMap for OrderedReverse {
    type Input = OrderedSpec;
    type Output = (bool, (Option<int>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.first, (value.second, ()))
    }
}

impl<'a> Map<(bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))> for OrderedForward {
    type O = Ordered<'a>;
    fn map(&self, input: (bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))) -> (value: Self::O) {
        let (first, (second, _end)) = input;
        Ordered {
            first,
            second,
        }
    }
}

impl<'a, 'x> Map<&'x Ordered<'a>> for OrderedReverse {
    type O = (&'x bool, (Option<&'x vest_lib2::asn1::Integer<'a>>, ()));
    fn map(&self, value: &'x Ordered<'a>) -> (output: Self::O) {
        (&value.first, (value.second.as_ref(), ()))
    }
}

#[derive(Clone, Copy)]
pub struct OuterForward;
#[derive(Clone, Copy)]
pub struct OuterReverse;

impl SpecMap for OuterForward {
    type Input = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    type Output = OuterSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        OuterSpec {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }
}

impl SpecMap for OuterReverse {
    type Input = OuterSpec;
    type Output = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.shared, (value.canonical, (value.ordered, (value.trailing, ()))))
    }
}

impl<'a> Map<(Shared, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))> for OuterForward {
    type O = Outer<'a>;
    fn map(&self, input: (Shared, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))) -> (value: Self::O) {
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        Outer {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }
}

impl<'a, 'x> Map<&'x Outer<'a>> for OuterReverse {
    type O = (&'x Shared, (&'x Canonical<'a>, (&'x Ordered<'a>, (Option<&'x vest_lib2::asn1::AnyOwned>, ()))));
    fn map(&self, value: &'x Outer<'a>) -> (output: Self::O) {
        (&value.shared, (&value.canonical, (&value.ordered, (value.trailing.as_ref(), ()))))
    }
}

/// BER format for ASN.1 `Version`.
type VERSION__ = Refined<vest_lib2::asn1::ber::Integer8TlvFmt, IntegerRange<true, 0, true, 1>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct VERSION(pub Class, pub u64);
impl VERSION {
    pub const Fmt: Self = Self(Class::Universal, 2u64);

    pub open spec fn spec_inner(&self) -> VERSION__ {
        use vest_lib2::asn1::ber::INTEGER8;
        let fmt = Refined(INTEGER8, IntegerRange::<true, 0, true, 1>);
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: VERSION__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::ber::INTEGER8;
        let fmt = Refined(INTEGER8, IntegerRange::<true, 0, true, 1>);
        fmt.retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// DER format for ASN.1 `Version-der`.
type VERSION_DER__ = Refined<vest_lib2::asn1::der::Integer8TlvFmt, IntegerRange<true, 0, true, 1>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct VERSION_DER(pub Class, pub u64);
impl VERSION_DER {
    pub const Fmt: Self = Self(Class::Universal, 2u64);

    pub open spec fn spec_inner(&self) -> VERSION_DER__ {
        use vest_lib2::asn1::der::INTEGER8;
        let fmt = Refined(INTEGER8, IntegerRange::<true, 0, true, 1>);
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: VERSION_DER__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::der::INTEGER8;
        let fmt = Refined(INTEGER8, IntegerRange::<true, 0, true, 1>);
        fmt.retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// BER format for ASN.1 `Shared`.
type SHARED__ = Mapped<vest_lib2::asn1::ber::SequenceFmt<vest_lib2::asn1::ber::DefaultFmt<VERSION, i8, Pair<Ref<vest_lib2::asn1::ber::OctetStringTlvFmt>, vest_lib2::asn1::ber::BerEndFmt>>>, BiMap<SharedForward, SharedReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct SHARED(pub Class, pub u64);
impl SHARED {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    pub open spec fn spec_inner(&self) -> SHARED__ {
        use vest_lib2::asn1::ber::{BER_END, DEFAULT, OCTET_STRING, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    DEFAULT(VERSION::Fmt, 0i8,
                    REQUIRED(Ref(OCTET_STRING),
                    BER_END)),
                ),
            mapper: BiMap(SharedForward, SharedReverse),
        };
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: SHARED__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::ber::{BER_END, DEFAULT, OCTET_STRING, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    DEFAULT(VERSION::Fmt, 0i8,
                    REQUIRED(Ref(OCTET_STRING),
                    BER_END)),
                ),
            mapper: BiMap(SharedForward, SharedReverse),
        };
        fmt.retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// DER format for ASN.1 `Shared-der`.
type SHARED_DER__ = Mapped<vest_lib2::asn1::der::SequenceFmt<vest_lib2::asn1::der::DefaultFmt<VERSION_DER, i8, Pair<Ref<vest_lib2::asn1::der::OctetStringTlvFmt>, Eof>>>, BiMap<SharedDerForward, SharedDerReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct SHARED_DER(pub Class, pub u64);
impl SHARED_DER {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    pub open spec fn spec_inner(&self) -> SHARED_DER__ {
        use vest_lib2::asn1::der::{DEFAULT, OCTET_STRING, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    DEFAULT(VERSION_DER::Fmt, 0i8,
                    REQUIRED(Ref(OCTET_STRING),
                    Eof)),
                ),
            mapper: BiMap(SharedDerForward, SharedDerReverse),
        };
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: SHARED_DER__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::der::{DEFAULT, OCTET_STRING, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    DEFAULT(VERSION_DER::Fmt, 0i8,
                    REQUIRED(Ref(OCTET_STRING),
                    Eof)),
                ),
            mapper: BiMap(SharedDerForward, SharedDerReverse),
        };
        fmt.retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// DER format for ASN.1 `Canonical`.
type CANONICAL__ = vest_lib2::asn1::der::SetOfTlvFmt<SHARED_DER>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct CANONICAL(pub Class, pub u64);
impl CANONICAL {
    pub const Fmt: Self = Self(Class::Universal, 17u64);

    pub open spec fn spec_inner(&self) -> CANONICAL__ {
        use vest_lib2::asn1::der::SET_OF;
        let fmt = SET_OF(SHARED_DER::Fmt);
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: CANONICAL__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::der::SET_OF;
        let fmt = SET_OF(SHARED_DER::Fmt);
        fmt.retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// DER format for ASN.1 `Ordered`.
type ORDERED__ = Mapped<vest_lib2::asn1::der::SetFmt<Pair<ImplicitFmt<Ref<vest_lib2::asn1::der::BoolTlvFmt>>, Optional<ImplicitFmt<Ref<vest_lib2::asn1::der::IntegerTlvFmt>>, Eof>>>, BiMap<OrderedForward, OrderedReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct ORDERED(pub Class, pub u64);
impl ORDERED {
    pub const Fmt: Self = Self(Class::Universal, 17u64);

    pub open spec fn spec_inner(&self) -> ORDERED__ {
        use vest_lib2::asn1::der::{BOOLEAN, INTEGER, SET};
        let fmt = Mapped {
            inner:
                SET(
                    REQUIRED(IMPLICIT(0u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(1u64, Ref(INTEGER)),
                    Eof)),
                ),
            mapper: BiMap(OrderedForward, OrderedReverse),
        };
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: ORDERED__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::der::{BOOLEAN, INTEGER, SET};
        let fmt = Mapped {
            inner:
                SET(
                    REQUIRED(IMPLICIT(0u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(1u64, Ref(INTEGER)),
                    Eof)),
                ),
            mapper: BiMap(OrderedForward, OrderedReverse),
        };
        fmt.retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// BER format for ASN.1 `Outer`.
type OUTER__ = Mapped<vest_lib2::asn1::ber::SequenceFmt<Pair<Ref<SHARED>, Pair<ImplicitFmt<Ref<CANONICAL>>, Pair<vest_lib2::asn1::ber::ExplicitFmt<Ref<ORDERED>>, Optional<Ref<vest_lib2::asn1::ber::AnyTlvFmt>, vest_lib2::asn1::ber::BerEndFmt>>>>>, BiMap<OuterForward, OuterReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct OUTER(pub Class, pub u64);
impl OUTER {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    pub open spec fn spec_inner(&self) -> OUTER__ {
        use vest_lib2::asn1::ber::{ANY, BER_END, EXPLICIT, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    REQUIRED(Ref(SHARED::Fmt),
                    REQUIRED(IMPLICIT(0u64, Ref(CANONICAL::Fmt)),
                    REQUIRED(EXPLICIT(1u64, Ref(ORDERED::Fmt)),
                    OPTIONAL(Ref(ANY),
                    BER_END)))),
                ),
            mapper: BiMap(OuterForward, OuterReverse),
        };
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: OUTER__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::ber::{ANY, BER_END, EXPLICIT, SEQUENCE};
        let fmt = Mapped {
            inner:
                SEQUENCE(
                    REQUIRED(Ref(SHARED::Fmt),
                    REQUIRED(IMPLICIT(0u64, Ref(CANONICAL::Fmt)),
                    REQUIRED(EXPLICIT(1u64, Ref(ORDERED::Fmt)),
                    OPTIONAL(Ref(ANY),
                    BER_END)))),
                ),
            mapper: BiMap(OuterForward, OuterReverse),
        };
        fmt.retagged(Tag {
            class: self.0,
            constructed: true,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// BER format for ASN.1 `NumericLabel`.
type NUMERIC_LABEL__ = Refined<vest_lib2::asn1::ber::NumericStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct NUMERIC_LABEL(pub Class, pub u64);
impl NUMERIC_LABEL {
    pub const Fmt: Self = Self(Class::Universal, 18u64);

    pub open spec fn spec_inner(&self) -> NUMERIC_LABEL__ {
        use vest_lib2::asn1::ber::NUMERIC_STRING;
        let fmt = Refined(NUMERIC_STRING, Size::<true, 1, true, 16>);
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: NUMERIC_LABEL__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::ber::NUMERIC_STRING;
        let fmt = Refined(NUMERIC_STRING, Size::<true, 1, true, 16>);
        fmt.retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }
}

/// BER format for ASN.1 `UniversalLabel`.
type UNIVERSAL_LABEL__ = Refined<vest_lib2::asn1::ber::UniversalStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct UNIVERSAL_LABEL(pub Class, pub u64);
impl UNIVERSAL_LABEL {
    pub const Fmt: Self = Self(Class::Universal, 28u64);

    pub open spec fn spec_inner(&self) -> UNIVERSAL_LABEL__ {
        use vest_lib2::asn1::ber::UNIVERSAL_STRING;
        let fmt = Refined(UNIVERSAL_STRING, Size::<true, 1, true, 16>);
        fmt.spec_retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }

    pub fn exec_inner(&self) -> (fmt: UNIVERSAL_LABEL__)
        ensures fmt == self.spec_inner(),
    {
        use vest_lib2::asn1::ber::UNIVERSAL_STRING;
        let fmt = Refined(UNIVERSAL_STRING, Size::<true, 1, true, 16>);
        fmt.retagged(Tag {
            class: self.0,
            constructed: false,
            number: tag_num_from_uint(self.1),
        })
    }
}


} // verus!

vest_lib2::impl_ber!(tagged, owned, VERSION, VERSION__, VersionSpec, Version);

vest_lib2::impl_der!(tagged, owned, VERSION_DER, VERSION_DER__, VersionDerSpec, VersionDer);

vest_lib2::impl_ber!(tagged, owned, SHARED, SHARED__, SharedSpec, Shared);

vest_lib2::impl_der!(tagged, borrowed, SHARED_DER, SHARED_DER__, SharedDerSpec, SharedDer);

vest_lib2::impl_der!(tagged, borrowed, CANONICAL, CANONICAL__, CanonicalSpec, Canonical);

vest_lib2::impl_der!(tagged, borrowed, ORDERED, ORDERED__, OrderedSpec, Ordered);

vest_lib2::impl_ber!(tagged, borrowed, OUTER, OUTER__, OuterSpec, Outer);

vest_lib2::impl_ber!(tagged, owned, NUMERIC_LABEL, NUMERIC_LABEL__, NumericLabelSpec, NumericLabel);

vest_lib2::impl_ber!(tagged, owned, UNIVERSAL_LABEL, UNIVERSAL_LABEL__, UniversalLabelSpec, UniversalLabel);
