// @generated by vestasn1 from ASN.1 module `BerFixture`.
// Generated formats parse and serialize BER.
#![allow(unused_imports)]

use vest_lib2::asn1::*;
use vest_lib2::asn1::ber::{AnyTlvFmt, BitStringTlvFmt, BmpStringTlvFmt, BoolTlvFmt, DefaultFmt, Enumerated16TlvFmt, EnumeratedTlvFmt, Explicit, ExplicitFmt, GeneralizedTimeTlvFmt, Ia5StringTlvFmt, Implicit, ImplicitFmt, Integer16TlvFmt, Integer8TlvFmt, IntegerTlvFmt, NullTlvFmt, ObjectIdentifierTlvFmt, OctetStringTlvFmt, PrintableStringTlvFmt, RealTlvFmt, SequenceFmt, SequenceOfFmt, SetOfTlvFmt, TeletexStringTlvFmt, UtcTimeTlvFmt, Utf8StringTlvFmt, ANY, BIT_STRING, BMP_STRING, BOOLEAN, CHOICE, DEFAULT, ENUMERATED, ENUMERATED16, EXPLICIT, EXPLICIT_APPLICATION, EXPLICIT_PRIVATE, GENERALIZED_TIME, IA5_STRING, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, INTEGER, INTEGER16, INTEGER8, NULL, OBJECT_IDENTIFIER, OCTET_STRING, OPTIONAL, PRINTABLE_STRING, REAL, REQUIRED, SEQUENCE, SEQUENCE_OF, SET_OF, TELETEX_STRING, UTC_TIME, UTF8_STRING};
use vest_lib2::asn1::ber::{BerEndFmt, BER_END};
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::combinators::Eof;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Payload = Vec<u8>;
pub type PayloadSpec = Seq<u8>;

pub type Bits = vest_lib2::asn1::BitStringOwned;
pub type BitsSpec = vest_lib2::asn1::BitStringSpec;

pub type Label = String;
pub type LabelSpec = Seq<char>;

pub type Printable = vest_lib2::asn1::PrintableStringOwned;
pub type PrintableSpec = vest_lib2::asn1::PrintableStringSpec;

pub type Ascii = vest_lib2::asn1::Ia5StringOwned;
pub type AsciiSpec = vest_lib2::asn1::Ia5StringSpec;

pub type Legacy = vest_lib2::asn1::TeletexStringOwned;
pub type LegacySpec = vest_lib2::asn1::TeletexStringSpec;

pub type Wide = vest_lib2::asn1::BmpString;
pub type WideSpec = vest_lib2::asn1::BmpStringSpec;

pub type OpenValue = vest_lib2::asn1::AnyOwned;
pub type OpenValueSpec = vest_lib2::asn1::AnySpec;

/// Value type for ASN.1 `Item`.
pub struct Item {
    pub payload: Payload,
    pub bits: Bits,
    pub label: Label,
    pub printable: Option<Printable>,
    pub open: Option<OpenValue>,
}

#[verifier::ext_equal]
pub struct ItemSpec {
    pub payload: PayloadSpec,
    pub bits: BitsSpec,
    pub label: LabelSpec,
    pub printable: Option<PrintableSpec>,
    pub open: Option<OpenValueSpec>,
}

impl DeepView for Item {
    type V = ItemSpec;
    open spec fn deep_view(&self) -> Self::V {
        ItemSpec {
            payload: self.payload.deep_view(),
            bits: self.bits.deep_view(),
            label: self.label.deep_view(),
            printable: self.printable.deep_view(),
            open: self.open.deep_view(),
        }
    }
}

/// Value type for ASN.1 `AutomationChoice`.
pub enum AutomationChoice {
    BooleanValue(bool),
    OctetsValue(Vec<u8>),
    BitsValue(vest_lib2::asn1::BitStringOwned),
    TextValue(String),
    PrintableValue(vest_lib2::asn1::PrintableStringOwned),
    OpenValue(vest_lib2::asn1::AnyOwned),
}

#[verifier::ext_equal]
pub enum AutomationChoiceSpec {
    BooleanValue(bool),
    OctetsValue(Seq<u8>),
    BitsValue(vest_lib2::asn1::BitStringSpec),
    TextValue(Seq<char>),
    PrintableValue(vest_lib2::asn1::PrintableStringSpec),
    OpenValue(vest_lib2::asn1::AnySpec),
}

impl DeepView for AutomationChoice {
    type V = AutomationChoiceSpec;
    open spec fn deep_view(&self) -> Self::V {
        match self {
            AutomationChoice::BooleanValue(value) => AutomationChoiceSpec::BooleanValue(value.deep_view()),
            AutomationChoice::OctetsValue(value) => AutomationChoiceSpec::OctetsValue(value.deep_view()),
            AutomationChoice::BitsValue(value) => AutomationChoiceSpec::BitsValue(value.deep_view()),
            AutomationChoice::TextValue(value) => AutomationChoiceSpec::TextValue(value.deep_view()),
            AutomationChoice::PrintableValue(value) => AutomationChoiceSpec::PrintableValue(value.deep_view()),
            AutomationChoice::OpenValue(value) => AutomationChoiceSpec::OpenValue(value.deep_view()),
        }
    }
}

/// Value type for ASN.1 `AutomationSequence`.
pub struct AutomationSequence {
    pub prefix: Option<bool>,
    pub enabled: bool,
    pub payload: Option<Vec<u8>>,
    pub marker: bool,
    pub selected: Option<AutomationChoice>,
}

#[verifier::ext_equal]
pub struct AutomationSequenceSpec {
    pub prefix: Option<bool>,
    pub enabled: bool,
    pub payload: Option<Seq<u8>>,
    pub marker: bool,
    pub selected: Option<AutomationChoiceSpec>,
}

impl DeepView for AutomationSequence {
    type V = AutomationSequenceSpec;
    open spec fn deep_view(&self) -> Self::V {
        AutomationSequenceSpec {
            prefix: self.prefix.deep_view(),
            enabled: self.enabled.deep_view(),
            payload: self.payload.deep_view(),
            marker: self.marker.deep_view(),
            selected: self.selected.deep_view(),
        }
    }
}

pub type Items = Vec<Item>;
pub type ItemsSpec = Seq<ItemSpec>;

pub type Flags = Vec<bool>;
pub type FlagsSpec = Seq<bool>;

#[derive(Clone, Copy)]
pub struct ItemForward;
#[derive(Clone, Copy)]
pub struct ItemReverse;

impl SpecMap for ItemForward {
    type Input = (PayloadSpec, (BitsSpec, (LabelSpec, (Option<PrintableSpec>, (Option<OpenValueSpec>, ())))));
    type Output = ItemSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (payload, (bits, (label, (printable, (open, _end))))) = input;
        ItemSpec {
            payload,
            bits,
            label,
            printable,
            open,
        }
    }
}

impl SpecMap for ItemReverse {
    type Input = ItemSpec;
    type Output = (PayloadSpec, (BitsSpec, (LabelSpec, (Option<PrintableSpec>, (Option<OpenValueSpec>, ())))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.payload, (value.bits, (value.label, (value.printable, (value.open, ())))))
    }
}

impl Map<(Payload, (Bits, (Label, (Option<Printable>, (Option<OpenValue>, ())))))> for ItemForward {
    type O = Item;
    fn map(&self, input: (Payload, (Bits, (Label, (Option<Printable>, (Option<OpenValue>, ())))))) -> (value: Self::O) {
        let (payload, (bits, (label, (printable, (open, _end))))) = input;
        Item {
            payload,
            bits,
            label,
            printable,
            open,
        }
    }
}

impl<'x> Map<&'x Item> for ItemReverse {
    type O = (&'x Payload, (&'x Bits, (&'x Label, (Option<&'x Printable>, (Option<&'x OpenValue>, ())))));
    fn map(&self, value: &'x Item) -> (output: Self::O) {
        (&value.payload, (&value.bits, (&value.label, (value.printable.as_ref(), (value.open.as_ref(), ())))))
    }
}

#[derive(Clone, Copy)]
pub struct AutomationChoiceForward;
#[derive(Clone, Copy)]
pub struct AutomationChoiceReverse;

impl SpecMap for AutomationChoiceForward {
    type Input = Sum<bool, Sum<Seq<u8>, Sum<vest_lib2::asn1::BitStringSpec, Sum<Seq<char>, Sum<vest_lib2::asn1::PrintableStringSpec, vest_lib2::asn1::AnySpec>>>>>;
    type Output = AutomationChoiceSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        match input {
            Sum::Inl(value) => AutomationChoiceSpec::BooleanValue(value),
            Sum::Inr(Sum::Inl(value)) => AutomationChoiceSpec::OctetsValue(value),
            Sum::Inr(Sum::Inr(Sum::Inl(value))) => AutomationChoiceSpec::BitsValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value)))) => AutomationChoiceSpec::TextValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value))))) => AutomationChoiceSpec::PrintableValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(value))))) => AutomationChoiceSpec::OpenValue(value),
        }
    }
}

impl SpecMap for AutomationChoiceReverse {
    type Input = AutomationChoiceSpec;
    type Output = Sum<bool, Sum<Seq<u8>, Sum<vest_lib2::asn1::BitStringSpec, Sum<Seq<char>, Sum<vest_lib2::asn1::PrintableStringSpec, vest_lib2::asn1::AnySpec>>>>>;
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        match value {
            AutomationChoiceSpec::BooleanValue(value) => Sum::Inl(value),
            AutomationChoiceSpec::OctetsValue(value) => Sum::Inr(Sum::Inl(value)),
            AutomationChoiceSpec::BitsValue(value) => Sum::Inr(Sum::Inr(Sum::Inl(value))),
            AutomationChoiceSpec::TextValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value)))),
            AutomationChoiceSpec::PrintableValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value))))),
            AutomationChoiceSpec::OpenValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(value))))),
        }
    }
}

impl Map<Sum<bool, Sum<Vec<u8>, Sum<vest_lib2::asn1::BitStringOwned, Sum<String, Sum<vest_lib2::asn1::PrintableStringOwned, vest_lib2::asn1::AnyOwned>>>>>> for AutomationChoiceForward {
    type O = AutomationChoice;
    fn map(&self, input: Sum<bool, Sum<Vec<u8>, Sum<vest_lib2::asn1::BitStringOwned, Sum<String, Sum<vest_lib2::asn1::PrintableStringOwned, vest_lib2::asn1::AnyOwned>>>>>) -> (value: Self::O) {
        match input {
            Sum::Inl(value) => AutomationChoice::BooleanValue(value),
            Sum::Inr(Sum::Inl(value)) => AutomationChoice::OctetsValue(value),
            Sum::Inr(Sum::Inr(Sum::Inl(value))) => AutomationChoice::BitsValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value)))) => AutomationChoice::TextValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value))))) => AutomationChoice::PrintableValue(value),
            Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(value))))) => AutomationChoice::OpenValue(value),
        }
    }
}

impl<'x> Map<&'x AutomationChoice> for AutomationChoiceReverse {
    type O = Sum<&'x bool, Sum<&'x Vec<u8>, Sum<&'x vest_lib2::asn1::BitStringOwned, Sum<&'x String, Sum<&'x vest_lib2::asn1::PrintableStringOwned, &'x vest_lib2::asn1::AnyOwned>>>>>;
    fn map(&self, value: &'x AutomationChoice) -> (output: Self::O) {
        match value {
            AutomationChoice::BooleanValue(value) => Sum::Inl(value),
            AutomationChoice::OctetsValue(value) => Sum::Inr(Sum::Inl(value)),
            AutomationChoice::BitsValue(value) => Sum::Inr(Sum::Inr(Sum::Inl(value))),
            AutomationChoice::TextValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value)))),
            AutomationChoice::PrintableValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inl(value))))),
            AutomationChoice::OpenValue(value) => Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(Sum::Inr(value))))),
        }
    }
}

#[derive(Clone, Copy)]
pub struct AutomationSequenceForward;
#[derive(Clone, Copy)]
pub struct AutomationSequenceReverse;

impl SpecMap for AutomationSequenceForward {
    type Input = (Option<bool>, (bool, (Option<Seq<u8>>, (bool, (Option<AutomationChoiceSpec>, ())))));
    type Output = AutomationSequenceSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (prefix, (enabled, (payload, (marker, (selected, _end))))) = input;
        AutomationSequenceSpec {
            prefix,
            enabled,
            payload,
            marker,
            selected,
        }
    }
}

impl SpecMap for AutomationSequenceReverse {
    type Input = AutomationSequenceSpec;
    type Output = (Option<bool>, (bool, (Option<Seq<u8>>, (bool, (Option<AutomationChoiceSpec>, ())))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.prefix, (value.enabled, (value.payload, (value.marker, (value.selected, ())))))
    }
}

impl Map<(Option<bool>, (bool, (Option<Vec<u8>>, (bool, (Option<AutomationChoice>, ())))))> for AutomationSequenceForward {
    type O = AutomationSequence;
    fn map(&self, input: (Option<bool>, (bool, (Option<Vec<u8>>, (bool, (Option<AutomationChoice>, ())))))) -> (value: Self::O) {
        let (prefix, (enabled, (payload, (marker, (selected, _end))))) = input;
        AutomationSequence {
            prefix,
            enabled,
            payload,
            marker,
            selected,
        }
    }
}

impl<'x> Map<&'x AutomationSequence> for AutomationSequenceReverse {
    type O = (Option<&'x bool>, (bool, (Option<&'x Vec<u8>>, (&'x bool, (Option<&'x AutomationChoice>, ())))));
    fn map(&self, value: &'x AutomationSequence) -> (output: Self::O) {
        (value.prefix.as_ref(), (value.enabled, (value.payload.as_ref(), (&value.marker, (value.selected.as_ref(), ())))))
    }
}

/// BER format for ASN.1 `Payload`.
pub type PayloadFmt = Refined<OctetStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn PAYLOAD_FMT() -> PayloadFmt
    returns
        (
            Refined(OCTET_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(OCTET_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `Bits`.
pub type BitsFmt = BitStringTlvFmt;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn BITS_FMT() -> BitsFmt
    returns
        (
            BIT_STRING
        ),
{
    BIT_STRING
}

/// BER format for ASN.1 `Label`.
pub type LabelFmt = Refined<Utf8StringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn LABEL_FMT() -> LabelFmt
    returns
        (
            Refined(UTF8_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(UTF8_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `Printable`.
pub type PrintableFmt = Refined<PrintableStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn PRINTABLE_FMT() -> PrintableFmt
    returns
        (
            Refined(PRINTABLE_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(PRINTABLE_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `Ascii`.
pub type AsciiFmt = Refined<Ia5StringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ASCII_FMT() -> AsciiFmt
    returns
        (
            Refined(IA5_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(IA5_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `Legacy`.
pub type LegacyFmt = Refined<TeletexStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn LEGACY_FMT() -> LegacyFmt
    returns
        (
            Refined(TELETEX_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(TELETEX_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `Wide`.
pub type WideFmt = Refined<BmpStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn WIDE_FMT() -> WideFmt
    returns
        (
            Refined(BMP_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(BMP_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `OpenValue`.
pub type OpenValueFmt = AnyTlvFmt;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn OPEN_VALUE_FMT() -> OpenValueFmt
    returns
        (
            ANY
        ),
{
    ANY
}

/// BER format for ASN.1 `Item`.
pub type ItemFmt = Mapped<SequenceFmt<Pair<Ref<PayloadFmt>, Pair<ImplicitFmt<Ref<BitsFmt>>, Pair<ImplicitFmt<Ref<LabelFmt>>, Optional<ImplicitFmt<Ref<PrintableFmt>>, Optional<ExplicitFmt<Ref<OpenValueFmt>>, BerEndFmt>>>>>>, BiMap<ItemForward, ItemReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ITEM_FMT() -> ItemFmt
    returns
        (
            Mapped {
                inner:
                    SEQUENCE(
                        REQUIRED(Ref(PAYLOAD_FMT()),
                        REQUIRED(IMPLICIT(0u64, Ref(BITS_FMT())),
                        REQUIRED(IMPLICIT(1u64, Ref(LABEL_FMT())),
                        OPTIONAL(IMPLICIT(2u64, Ref(PRINTABLE_FMT())),
                        OPTIONAL(EXPLICIT(3u64, Ref(OPEN_VALUE_FMT())),
                        BER_END))))),
                    ),
                mapper: BiMap(ItemForward, ItemReverse),
            }
        ),
{
    Mapped {
        inner:
            SEQUENCE(
                REQUIRED(Ref(PAYLOAD_FMT()),
                REQUIRED(IMPLICIT(0u64, Ref(BITS_FMT())),
                REQUIRED(IMPLICIT(1u64, Ref(LABEL_FMT())),
                OPTIONAL(IMPLICIT(2u64, Ref(PRINTABLE_FMT())),
                OPTIONAL(EXPLICIT(3u64, Ref(OPEN_VALUE_FMT())),
                BER_END))))),
            ),
        mapper: BiMap(ItemForward, ItemReverse),
    }
}

/// BER format for ASN.1 `AutomationChoice`.
pub type AutomationChoiceFmt = Mapped<Choice<ImplicitFmt<Ref<BoolTlvFmt>>, Choice<ImplicitFmt<Ref<OctetStringTlvFmt>>, Choice<ImplicitFmt<Ref<BitStringTlvFmt>>, Choice<ImplicitFmt<Ref<Utf8StringTlvFmt>>, Choice<ImplicitFmt<Ref<PrintableStringTlvFmt>>, ExplicitFmt<Ref<AnyTlvFmt>>>>>>>, BiMap<AutomationChoiceForward, AutomationChoiceReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn AUTOMATION_CHOICE_FMT() -> AutomationChoiceFmt
    returns
        (
            Mapped {
                inner:
                    CHOICE(
                        IMPLICIT(10u64, Ref(BOOLEAN)), CHOICE(
                        IMPLICIT(11u64, Ref(OCTET_STRING)), CHOICE(
                        IMPLICIT(12u64, Ref(BIT_STRING)), CHOICE(
                        IMPLICIT(13u64, Ref(UTF8_STRING)), CHOICE(
                        IMPLICIT(14u64, Ref(PRINTABLE_STRING)),
                        EXPLICIT(15u64, Ref(ANY))))))),
                mapper: BiMap(AutomationChoiceForward, AutomationChoiceReverse),
            }
        ),
{
    Mapped {
        inner:
            CHOICE(
                IMPLICIT(10u64, Ref(BOOLEAN)), CHOICE(
                IMPLICIT(11u64, Ref(OCTET_STRING)), CHOICE(
                IMPLICIT(12u64, Ref(BIT_STRING)), CHOICE(
                IMPLICIT(13u64, Ref(UTF8_STRING)), CHOICE(
                IMPLICIT(14u64, Ref(PRINTABLE_STRING)),
                EXPLICIT(15u64, Ref(ANY))))))),
        mapper: BiMap(AutomationChoiceForward, AutomationChoiceReverse),
    }
}

/// BER format for ASN.1 `AutomationSequence`.
pub type AutomationSequenceFmt = Mapped<SequenceFmt<Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Optional<ExplicitFmt<Ref<OctetStringTlvFmt>>, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ExplicitFmt<Ref<AutomationChoiceFmt>>, BerEndFmt>>>>>>, BiMap<AutomationSequenceForward, AutomationSequenceReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn AUTOMATION_SEQUENCE_FMT() -> AutomationSequenceFmt
    returns
        (
            Mapped {
                inner:
                    SEQUENCE(
                        OPTIONAL(IMPLICIT(20u64, Ref(BOOLEAN)),
                        DEFAULT(IMPLICIT(21u64, BOOLEAN), true,
                        OPTIONAL(EXPLICIT(22u64, Ref(OCTET_STRING)),
                        REQUIRED(IMPLICIT(23u64, Ref(BOOLEAN)),
                        OPTIONAL(EXPLICIT(24u64, Ref(AUTOMATION_CHOICE_FMT())),
                        BER_END))))),
                    ),
                mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
            }
        ),
{
    Mapped {
        inner:
            SEQUENCE(
                OPTIONAL(IMPLICIT(20u64, Ref(BOOLEAN)),
                DEFAULT(IMPLICIT(21u64, BOOLEAN), true,
                OPTIONAL(EXPLICIT(22u64, Ref(OCTET_STRING)),
                REQUIRED(IMPLICIT(23u64, Ref(BOOLEAN)),
                OPTIONAL(EXPLICIT(24u64, Ref(AUTOMATION_CHOICE_FMT())),
                BER_END))))),
            ),
        mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
    }
}

/// BER format for ASN.1 `Items`.
pub type ItemsFmt = SequenceOfFmt<ItemFmt>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ITEMS_FMT() -> ItemsFmt
    returns
        (
            SEQUENCE_OF(ITEM_FMT())
        ),
{
    SEQUENCE_OF(ITEM_FMT())
}

/// BER format for ASN.1 `Flags`.
pub type FlagsFmt = SequenceOfFmt<BoolTlvFmt>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn FLAGS_FMT() -> FlagsFmt
    returns
        (
            SEQUENCE_OF(BOOLEAN)
        ),
{
    SEQUENCE_OF(BOOLEAN)
}

proof fn vestasn1_generated_formats_are_valid() {
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(PAYLOAD_FMT().safe_inv());
    assert(PAYLOAD_FMT().unambiguous());
    assert(BITS_FMT().safe_inv());
    assert(BITS_FMT().unambiguous());
    assert(LABEL_FMT().safe_inv());
    assert(LABEL_FMT().unambiguous());
    assert(PRINTABLE_FMT().safe_inv());
    assert(PRINTABLE_FMT().unambiguous());
    assert(ASCII_FMT().safe_inv());
    assert(ASCII_FMT().unambiguous());
    assert(LEGACY_FMT().safe_inv());
    assert(LEGACY_FMT().unambiguous());
    assert(WIDE_FMT().safe_inv());
    assert(WIDE_FMT().unambiguous());
    assert(OPEN_VALUE_FMT().safe_inv());
    assert(OPEN_VALUE_FMT().unambiguous());
    assert(ITEM_FMT().safe_inv());
    assert(ITEM_FMT().unambiguous());
    assert(AUTOMATION_CHOICE_FMT().safe_inv());
    assert(AUTOMATION_CHOICE_FMT().unambiguous());
    assert(AUTOMATION_SEQUENCE_FMT().safe_inv());
    assert(AUTOMATION_SEQUENCE_FMT().unambiguous());
    assert(ITEMS_FMT().safe_inv());
    assert(ITEMS_FMT().unambiguous());
    assert(FLAGS_FMT().safe_inv());
    assert(FLAGS_FMT().unambiguous());
}


} // verus!
