// @generated by vestasn1 from ASN.1 module `MixedFixture`.
// Generated formats parse and serialize a schema-selected mixture of BER and DER.
#![allow(unused_imports)]

use vest_lib2::asn1::*;
use vest_lib2::asn1::modifiers::{implicitly_tagged as Implicit, ImplicitFmt, CHOICE, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, OPTIONAL, REQUIRED};
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::combinators::Eof;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Version = i8;
pub type VersionSpec = i8;

pub type VersionDer = i8;
pub type VersionDerSpec = i8;

/// Value type for ASN.1 `Shared`.
pub struct Shared {
    pub version: Version,
    pub payload: Vec<u8>,
}

#[verifier::ext_equal]
pub struct SharedSpec {
    pub version: VersionSpec,
    pub payload: Seq<u8>,
}

impl DeepView for Shared {
    type V = SharedSpec;
    open spec fn deep_view(&self) -> Self::V {
        SharedSpec {
            version: self.version.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Shared-der`.
pub struct SharedDer<'a> {
    pub version: VersionDer,
    pub payload: &'a [u8],
}

#[verifier::ext_equal]
pub struct SharedDerSpec {
    pub version: VersionDerSpec,
    pub payload: Seq<u8>,
}

impl<'a> DeepView for SharedDer<'a> {
    type V = SharedDerSpec;
    open spec fn deep_view(&self) -> Self::V {
        SharedDerSpec {
            version: self.version.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

pub type Canonical<'a> = Vec<SharedDer<'a>>;
pub type CanonicalSpec = Seq<SharedDerSpec>;

/// Value type for ASN.1 `Ordered`.
pub struct Ordered<'a> {
    pub first: bool,
    pub second: Option<vest_lib2::asn1::Integer<'a>>,
}

#[verifier::ext_equal]
pub struct OrderedSpec {
    pub first: bool,
    pub second: Option<int>,
}

impl<'a> DeepView for Ordered<'a> {
    type V = OrderedSpec;
    open spec fn deep_view(&self) -> Self::V {
        OrderedSpec {
            first: self.first.deep_view(),
            second: self.second.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Outer`.
pub struct Outer<'a> {
    pub shared: Shared,
    pub canonical: Canonical<'a>,
    pub ordered: Ordered<'a>,
    pub trailing: Option<vest_lib2::asn1::AnyOwned>,
}

#[verifier::ext_equal]
pub struct OuterSpec {
    pub shared: SharedSpec,
    pub canonical: CanonicalSpec,
    pub ordered: OrderedSpec,
    pub trailing: Option<vest_lib2::asn1::AnySpec>,
}

impl<'a> DeepView for Outer<'a> {
    type V = OuterSpec;
    open spec fn deep_view(&self) -> Self::V {
        OuterSpec {
            shared: self.shared.deep_view(),
            canonical: self.canonical.deep_view(),
            ordered: self.ordered.deep_view(),
            trailing: self.trailing.deep_view(),
        }
    }
}

pub type NumericLabel = vest_lib2::asn1::NumericStringOwned;
pub type NumericLabelSpec = vest_lib2::asn1::NumericStringSpec;

pub type UniversalLabel = vest_lib2::asn1::UniversalString;
pub type UniversalLabelSpec = vest_lib2::asn1::UniversalStringSpec;

#[derive(Clone, Copy)]
pub struct SharedForward;
#[derive(Clone, Copy)]
pub struct SharedReverse;

impl SpecMap for SharedForward {
    type Input = (VersionSpec, (Seq<u8>, ()));
    type Output = SharedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (version, (payload, _end)) = input;
        SharedSpec {
            version,
            payload,
        }
    }
}

impl SpecMap for SharedReverse {
    type Input = SharedSpec;
    type Output = (VersionSpec, (Seq<u8>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.version, (value.payload, ()))
    }
}

impl Map<(Version, (Vec<u8>, ()))> for SharedForward {
    type O = Shared;
    fn map(&self, input: (Version, (Vec<u8>, ()))) -> (value: Self::O) {
        let (version, (payload, _end)) = input;
        Shared {
            version,
            payload,
        }
    }
}

impl<'x> Map<&'x Shared> for SharedReverse {
    type O = (Version, (&'x Vec<u8>, ()));
    fn map(&self, value: &'x Shared) -> (output: Self::O) {
        (value.version, (&value.payload, ()))
    }
}

#[derive(Clone, Copy)]
pub struct SharedDerForward;
#[derive(Clone, Copy)]
pub struct SharedDerReverse;

impl SpecMap for SharedDerForward {
    type Input = (VersionDerSpec, (Seq<u8>, ()));
    type Output = SharedDerSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (version, (payload, _end)) = input;
        SharedDerSpec {
            version,
            payload,
        }
    }
}

impl SpecMap for SharedDerReverse {
    type Input = SharedDerSpec;
    type Output = (VersionDerSpec, (Seq<u8>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.version, (value.payload, ()))
    }
}

impl<'a> Map<(VersionDer, (&'a [u8], ()))> for SharedDerForward {
    type O = SharedDer<'a>;
    fn map(&self, input: (VersionDer, (&'a [u8], ()))) -> (value: Self::O) {
        let (version, (payload, _end)) = input;
        SharedDer {
            version,
            payload,
        }
    }
}

impl<'a, 'x> Map<&'x SharedDer<'a>> for SharedDerReverse {
    type O = (VersionDer, (&'x &'a [u8], ()));
    fn map(&self, value: &'x SharedDer<'a>) -> (output: Self::O) {
        (value.version, (&value.payload, ()))
    }
}

#[derive(Clone, Copy)]
pub struct OrderedForward;
#[derive(Clone, Copy)]
pub struct OrderedReverse;

impl SpecMap for OrderedForward {
    type Input = (bool, (Option<int>, ()));
    type Output = OrderedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (first, (second, _end)) = input;
        OrderedSpec {
            first,
            second,
        }
    }
}

impl SpecMap for OrderedReverse {
    type Input = OrderedSpec;
    type Output = (bool, (Option<int>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.first, (value.second, ()))
    }
}

impl<'a> Map<(bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))> for OrderedForward {
    type O = Ordered<'a>;
    fn map(&self, input: (bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))) -> (value: Self::O) {
        let (first, (second, _end)) = input;
        Ordered {
            first,
            second,
        }
    }
}

impl<'a, 'x> Map<&'x Ordered<'a>> for OrderedReverse {
    type O = (&'x bool, (Option<&'x vest_lib2::asn1::Integer<'a>>, ()));
    fn map(&self, value: &'x Ordered<'a>) -> (output: Self::O) {
        (&value.first, (value.second.as_ref(), ()))
    }
}

#[derive(Clone, Copy)]
pub struct OuterForward;
#[derive(Clone, Copy)]
pub struct OuterReverse;

impl SpecMap for OuterForward {
    type Input = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    type Output = OuterSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        OuterSpec {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }
}

impl SpecMap for OuterReverse {
    type Input = OuterSpec;
    type Output = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        (value.shared, (value.canonical, (value.ordered, (value.trailing, ()))))
    }
}

impl<'a> Map<(Shared, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))> for OuterForward {
    type O = Outer<'a>;
    fn map(&self, input: (Shared, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))) -> (value: Self::O) {
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        Outer {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }
}

impl<'a, 'x> Map<&'x Outer<'a>> for OuterReverse {
    type O = (&'x Shared, (&'x Canonical<'a>, (&'x Ordered<'a>, (Option<&'x vest_lib2::asn1::AnyOwned>, ()))));
    fn map(&self, value: &'x Outer<'a>) -> (output: Self::O) {
        (&value.shared, (&value.canonical, (&value.ordered, (value.trailing.as_ref(), ()))))
    }
}

/// BER format for ASN.1 `Version`.
pub type VersionFmt = Refined<vest_lib2::asn1::ber::Integer8TlvFmt, IntegerRange<true, 0, true, 1>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn VERSION_FMT() -> VersionFmt
    returns
        (
            Refined(vest_lib2::asn1::ber::INTEGER8, IntegerRange::<true, 0, true, 1>)
        ),
{
    Refined(vest_lib2::asn1::ber::INTEGER8, IntegerRange::<true, 0, true, 1>)
}

/// DER format for ASN.1 `Version-der`.
pub type VersionDerFmt = Refined<vest_lib2::asn1::der::Integer8TlvFmt, IntegerRange<true, 0, true, 1>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn VERSION_DER_FMT() -> VersionDerFmt
    returns
        (
            Refined(vest_lib2::asn1::der::INTEGER8, IntegerRange::<true, 0, true, 1>)
        ),
{
    Refined(vest_lib2::asn1::der::INTEGER8, IntegerRange::<true, 0, true, 1>)
}

/// BER format for ASN.1 `Shared`.
pub type SharedFmt = Mapped<vest_lib2::asn1::ber::SequenceFmt<vest_lib2::asn1::ber::DefaultFmt<VersionFmt, i8, Pair<Ref<vest_lib2::asn1::ber::OctetStringTlvFmt>, vest_lib2::asn1::ber::BerEndFmt>>>, BiMap<SharedForward, SharedReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn SHARED_FMT() -> SharedFmt
    returns
        (
            Mapped {
                inner:
                    vest_lib2::asn1::ber::SEQUENCE(
                        vest_lib2::asn1::ber::DEFAULT(
                            VERSION_FMT(),
                            0i8,
                            REQUIRED(Ref(vest_lib2::asn1::ber::OCTET_STRING),
                            vest_lib2::asn1::ber::BER_END),
                        ),
                    ),
                mapper: BiMap(SharedForward, SharedReverse),
            }
        ),
{
    Mapped {
        inner:
            vest_lib2::asn1::ber::SEQUENCE(
                vest_lib2::asn1::ber::DEFAULT(
                    VERSION_FMT(),
                    0i8,
                    REQUIRED(Ref(vest_lib2::asn1::ber::OCTET_STRING),
                    vest_lib2::asn1::ber::BER_END),
                ),
            ),
        mapper: BiMap(SharedForward, SharedReverse),
    }
}

/// DER format for ASN.1 `Shared-der`.
pub type SharedDerFmt = Mapped<vest_lib2::asn1::der::SequenceFmt<vest_lib2::asn1::der::DefaultFmt<VersionDerFmt, i8, Pair<Ref<vest_lib2::asn1::der::OctetStringTlvFmt>, Eof>>>, BiMap<SharedDerForward, SharedDerReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn SHARED_DER_FMT() -> SharedDerFmt
    returns
        (
            Mapped {
                inner:
                    vest_lib2::asn1::der::SEQUENCE(
                        vest_lib2::asn1::der::DEFAULT(
                            VERSION_DER_FMT(),
                            0i8,
                            REQUIRED(Ref(vest_lib2::asn1::der::OCTET_STRING),
                            Eof),
                        ),
                    ),
                mapper: BiMap(SharedDerForward, SharedDerReverse),
            }
        ),
{
    Mapped {
        inner:
            vest_lib2::asn1::der::SEQUENCE(
                vest_lib2::asn1::der::DEFAULT(
                    VERSION_DER_FMT(),
                    0i8,
                    REQUIRED(Ref(vest_lib2::asn1::der::OCTET_STRING),
                    Eof),
                ),
            ),
        mapper: BiMap(SharedDerForward, SharedDerReverse),
    }
}

/// DER format for ASN.1 `Canonical`.
pub type CanonicalFmt = vest_lib2::asn1::der::SetOfTlvFmt<SharedDerFmt>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn CANONICAL_FMT() -> CanonicalFmt
    returns
        (
            vest_lib2::asn1::der::SET_OF(SHARED_DER_FMT())
        ),
{
    vest_lib2::asn1::der::SET_OF(SHARED_DER_FMT())
}

/// DER format for ASN.1 `Ordered`.
pub type OrderedFmt = Mapped<vest_lib2::asn1::der::SetFmt<Pair<ImplicitFmt<Ref<vest_lib2::asn1::der::BoolTlvFmt>>, Optional<ImplicitFmt<Ref<vest_lib2::asn1::der::IntegerTlvFmt>>, Eof>>>, BiMap<OrderedForward, OrderedReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn ORDERED_FMT() -> OrderedFmt
    returns
        (
            Mapped {
                inner:
                    vest_lib2::asn1::der::SET(
                        REQUIRED(IMPLICIT(0u64, Ref(vest_lib2::asn1::der::BOOLEAN)),
                        OPTIONAL(IMPLICIT(1u64, Ref(vest_lib2::asn1::der::INTEGER)),
                        Eof)),
                    ),
                mapper: BiMap(OrderedForward, OrderedReverse),
            }
        ),
{
    Mapped {
        inner:
            vest_lib2::asn1::der::SET(
                REQUIRED(IMPLICIT(0u64, Ref(vest_lib2::asn1::der::BOOLEAN)),
                OPTIONAL(IMPLICIT(1u64, Ref(vest_lib2::asn1::der::INTEGER)),
                Eof)),
            ),
        mapper: BiMap(OrderedForward, OrderedReverse),
    }
}

/// BER format for ASN.1 `Outer`.
pub type OuterFmt = Mapped<vest_lib2::asn1::ber::SequenceFmt<Pair<Ref<SharedFmt>, Pair<ImplicitFmt<Ref<CanonicalFmt>>, Pair<vest_lib2::asn1::ber::ExplicitFmt<Ref<OrderedFmt>>, Optional<Ref<vest_lib2::asn1::ber::AnyTlvFmt>, vest_lib2::asn1::ber::BerEndFmt>>>>>, BiMap<OuterForward, OuterReverse>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn OUTER_FMT() -> OuterFmt
    returns
        (
            Mapped {
                inner:
                    vest_lib2::asn1::ber::SEQUENCE(
                        REQUIRED(Ref(SHARED_FMT()),
                        REQUIRED(IMPLICIT(0u64, Ref(CANONICAL_FMT())),
                        REQUIRED(vest_lib2::asn1::ber::EXPLICIT(1u64, Ref(ORDERED_FMT())),
                        OPTIONAL(Ref(vest_lib2::asn1::ber::ANY),
                        vest_lib2::asn1::ber::BER_END)))),
                    ),
                mapper: BiMap(OuterForward, OuterReverse),
            }
        ),
{
    Mapped {
        inner:
            vest_lib2::asn1::ber::SEQUENCE(
                REQUIRED(Ref(SHARED_FMT()),
                REQUIRED(IMPLICIT(0u64, Ref(CANONICAL_FMT())),
                REQUIRED(vest_lib2::asn1::ber::EXPLICIT(1u64, Ref(ORDERED_FMT())),
                OPTIONAL(Ref(vest_lib2::asn1::ber::ANY),
                vest_lib2::asn1::ber::BER_END)))),
            ),
        mapper: BiMap(OuterForward, OuterReverse),
    }
}

/// BER format for ASN.1 `NumericLabel`.
pub type NumericLabelFmt = Refined<vest_lib2::asn1::ber::NumericStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn NUMERIC_LABEL_FMT() -> NumericLabelFmt
    returns
        (
            Refined(vest_lib2::asn1::ber::NUMERIC_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(vest_lib2::asn1::ber::NUMERIC_STRING, Size::<true, 1, true, 16>)
}

/// BER format for ASN.1 `UniversalLabel`.
pub type UniversalLabelFmt = Refined<vest_lib2::asn1::ber::UniversalStringTlvFmt, Size<true, 1, true, 16>>;
#[verifier::allow_in_spec]
#[allow(non_snake_case)]
pub const fn UNIVERSAL_LABEL_FMT() -> UniversalLabelFmt
    returns
        (
            Refined(vest_lib2::asn1::ber::UNIVERSAL_STRING, Size::<true, 1, true, 16>)
        ),
{
    Refined(vest_lib2::asn1::ber::UNIVERSAL_STRING, Size::<true, 1, true, 16>)
}

/// Pure specification certificate for ASN.1 `Version`.
/// BER accepts non-canonical encodings, so `sound_inv` and `nonmal_inv` do not apply.
pub proof fn lemma_version_format_spec_invariants()
    ensures
        VERSION_FMT().safe_inv(),
        VERSION_FMT().productive_inv(),
        VERSION_FMT().serialize_inv(),
        VERSION_FMT().serialize_dps_inv(),
        VERSION_FMT().unambiguous(),
        VERSION_FMT().equiv_general_inv(),
        VERSION_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(VERSION_FMT().safe_inv());
    assert(VERSION_FMT().productive_inv());
    assert(VERSION_FMT().serialize_inv());
    assert(VERSION_FMT().serialize_dps_inv());
    assert(VERSION_FMT().unambiguous());
    assert(VERSION_FMT().equiv_general_inv());
    assert(VERSION_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Version`.
pub proof fn lemma_version_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <VersionFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&VERSION_FMT()),
        <VersionFmt as vest_lib2::core::exec::serializer::Serializer<Output, Version>>::exec_inv(&VERSION_FMT()),
        <VersionFmt as vest_lib2::core::exec::serializer::Prepare<Version>>::exec_inv(&VERSION_FMT()),
        <VersionFmt as vest_lib2::core::exec::serializer::ByteLen<Version>>::exec_inv(&VERSION_FMT()),
{
    lemma_version_format_spec_invariants();
    assert(<VersionFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&VERSION_FMT()));
    assert(<VersionFmt as vest_lib2::core::exec::serializer::Serializer<Output, Version>>::exec_inv(&VERSION_FMT()));
    assert(<VersionFmt as vest_lib2::core::exec::serializer::Prepare<Version>>::exec_inv(&VERSION_FMT()));
    assert(<VersionFmt as vest_lib2::core::exec::serializer::ByteLen<Version>>::exec_inv(&VERSION_FMT()));
}

/// Pure specification certificate for ASN.1 `Version-der`.
pub proof fn lemma_version_der_format_spec_invariants()
    ensures
        VERSION_DER_FMT().safe_inv(),
        VERSION_DER_FMT().productive_inv(),
        VERSION_DER_FMT().sound_inv(),
        VERSION_DER_FMT().nonmal_inv(),
        VERSION_DER_FMT().serialize_inv(),
        VERSION_DER_FMT().serialize_dps_inv(),
        VERSION_DER_FMT().unambiguous(),
        VERSION_DER_FMT().equiv_general_inv(),
        VERSION_DER_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(VERSION_DER_FMT().safe_inv());
    assert(VERSION_DER_FMT().productive_inv());
    assert(VERSION_DER_FMT().sound_inv());
    assert(VERSION_DER_FMT().nonmal_inv());
    assert(VERSION_DER_FMT().serialize_inv());
    assert(VERSION_DER_FMT().serialize_dps_inv());
    assert(VERSION_DER_FMT().unambiguous());
    assert(VERSION_DER_FMT().equiv_general_inv());
    assert(VERSION_DER_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Version-der`.
pub proof fn lemma_version_der_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <VersionDerFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&VERSION_DER_FMT()),
        <VersionDerFmt as vest_lib2::core::exec::serializer::Serializer<Output, VersionDer>>::exec_inv(&VERSION_DER_FMT()),
        <VersionDerFmt as vest_lib2::core::exec::serializer::Prepare<VersionDer>>::exec_inv(&VERSION_DER_FMT()),
        <VersionDerFmt as vest_lib2::core::exec::serializer::ByteLen<VersionDer>>::exec_inv(&VERSION_DER_FMT()),
{
    lemma_version_der_format_spec_invariants();
    assert(<VersionDerFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&VERSION_DER_FMT()));
    assert(<VersionDerFmt as vest_lib2::core::exec::serializer::Serializer<Output, VersionDer>>::exec_inv(&VERSION_DER_FMT()));
    assert(<VersionDerFmt as vest_lib2::core::exec::serializer::Prepare<VersionDer>>::exec_inv(&VERSION_DER_FMT()));
    assert(<VersionDerFmt as vest_lib2::core::exec::serializer::ByteLen<VersionDer>>::exec_inv(&VERSION_DER_FMT()));
}

/// Pure specification certificate for ASN.1 `Shared`.
/// BER accepts non-canonical encodings, so `sound_inv` and `nonmal_inv` do not apply.
pub proof fn lemma_shared_format_spec_invariants()
    ensures
        SHARED_FMT().safe_inv(),
        SHARED_FMT().productive_inv(),
        SHARED_FMT().serialize_inv(),
        SHARED_FMT().serialize_dps_inv(),
        SHARED_FMT().unambiguous(),
        SHARED_FMT().equiv_general_inv(),
        SHARED_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    lemma_version_format_spec_invariants();
    assert(SHARED_FMT().safe_inv());
    assert(SHARED_FMT().productive_inv());
    assert(SHARED_FMT().serialize_inv());
    assert(SHARED_FMT().serialize_dps_inv());
    assert(SHARED_FMT().unambiguous());
    assert(SHARED_FMT().equiv_general_inv());
    assert(SHARED_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Shared`.
pub proof fn lemma_shared_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <SharedFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&SHARED_FMT()),
        <SharedFmt as vest_lib2::core::exec::serializer::Serializer<Output, Shared>>::exec_inv(&SHARED_FMT()),
        <SharedFmt as vest_lib2::core::exec::serializer::Prepare<Shared>>::exec_inv(&SHARED_FMT()),
        <SharedFmt as vest_lib2::core::exec::serializer::ByteLen<Shared>>::exec_inv(&SHARED_FMT()),
{
    lemma_shared_format_spec_invariants();
    lemma_version_format_spec_invariants();
    lemma_version_format_exec_invariants::<Output>();
    assert(<SharedFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&SHARED_FMT()));
    assert(<SharedFmt as vest_lib2::core::exec::serializer::Serializer<Output, Shared>>::exec_inv(&SHARED_FMT()));
    assert(<SharedFmt as vest_lib2::core::exec::serializer::Prepare<Shared>>::exec_inv(&SHARED_FMT()));
    assert(<SharedFmt as vest_lib2::core::exec::serializer::ByteLen<Shared>>::exec_inv(&SHARED_FMT()));
}

/// Pure specification certificate for ASN.1 `Shared-der`.
pub proof fn lemma_shared_der_format_spec_invariants()
    ensures
        SHARED_DER_FMT().safe_inv(),
        SHARED_DER_FMT().productive_inv(),
        SHARED_DER_FMT().sound_inv(),
        SHARED_DER_FMT().nonmal_inv(),
        SHARED_DER_FMT().serialize_inv(),
        SHARED_DER_FMT().serialize_dps_inv(),
        SHARED_DER_FMT().unambiguous(),
        SHARED_DER_FMT().equiv_general_inv(),
        SHARED_DER_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    lemma_version_der_format_spec_invariants();
    assert(SHARED_DER_FMT().safe_inv());
    assert(SHARED_DER_FMT().productive_inv());
    assert(SHARED_DER_FMT().sound_inv());
    assert(SHARED_DER_FMT().nonmal_inv());
    assert(SHARED_DER_FMT().serialize_inv());
    assert(SHARED_DER_FMT().serialize_dps_inv());
    assert(SHARED_DER_FMT().unambiguous());
    assert(SHARED_DER_FMT().equiv_general_inv());
    assert(SHARED_DER_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Shared-der`.
pub proof fn lemma_shared_der_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <SharedDerFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&SHARED_DER_FMT()),
        <SharedDerFmt as vest_lib2::core::exec::serializer::Serializer<Output, SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()),
        <SharedDerFmt as vest_lib2::core::exec::serializer::Prepare<SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()),
        <SharedDerFmt as vest_lib2::core::exec::serializer::ByteLen<SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()),
{
    lemma_shared_der_format_spec_invariants();
    lemma_version_der_format_spec_invariants();
    lemma_version_der_format_exec_invariants::<Output>();
    assert(<SharedDerFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&SHARED_DER_FMT()));
    assert(<SharedDerFmt as vest_lib2::core::exec::serializer::Serializer<Output, SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()));
    assert(<SharedDerFmt as vest_lib2::core::exec::serializer::Prepare<SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()));
    assert(<SharedDerFmt as vest_lib2::core::exec::serializer::ByteLen<SharedDer<'i>>>::exec_inv(&SHARED_DER_FMT()));
}

/// Pure specification certificate for ASN.1 `Canonical`.
pub proof fn lemma_canonical_format_spec_invariants()
    ensures
        CANONICAL_FMT().safe_inv(),
        CANONICAL_FMT().productive_inv(),
        CANONICAL_FMT().sound_inv(),
        CANONICAL_FMT().nonmal_inv(),
        CANONICAL_FMT().serialize_inv(),
        CANONICAL_FMT().serialize_dps_inv(),
        CANONICAL_FMT().unambiguous(),
        CANONICAL_FMT().equiv_general_inv(),
        CANONICAL_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    lemma_shared_der_format_spec_invariants();
    assert(CANONICAL_FMT().safe_inv());
    assert(CANONICAL_FMT().productive_inv());
    assert(CANONICAL_FMT().sound_inv());
    assert(CANONICAL_FMT().nonmal_inv());
    assert(CANONICAL_FMT().serialize_inv());
    assert(CANONICAL_FMT().serialize_dps_inv());
    assert(CANONICAL_FMT().unambiguous());
    assert(CANONICAL_FMT().equiv_general_inv());
    assert(CANONICAL_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Canonical`.
pub proof fn lemma_canonical_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <CanonicalFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&CANONICAL_FMT()),
        <CanonicalFmt as vest_lib2::core::exec::serializer::Serializer<Output, Canonical<'i>>>::exec_inv(&CANONICAL_FMT()),
        <CanonicalFmt as vest_lib2::core::exec::serializer::Prepare<Canonical<'i>>>::exec_inv(&CANONICAL_FMT()),
        <CanonicalFmt as vest_lib2::core::exec::serializer::ByteLen<Canonical<'i>>>::exec_inv(&CANONICAL_FMT()),
{
    lemma_canonical_format_spec_invariants();
    lemma_shared_der_format_spec_invariants();
    lemma_shared_der_format_exec_invariants::<Output>();
    assert(<CanonicalFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&CANONICAL_FMT()));
    assert(<CanonicalFmt as vest_lib2::core::exec::serializer::Serializer<Output, Canonical<'i>>>::exec_inv(&CANONICAL_FMT()));
    assert(<CanonicalFmt as vest_lib2::core::exec::serializer::Prepare<Canonical<'i>>>::exec_inv(&CANONICAL_FMT()));
    assert(<CanonicalFmt as vest_lib2::core::exec::serializer::ByteLen<Canonical<'i>>>::exec_inv(&CANONICAL_FMT()));
}

/// Pure specification certificate for ASN.1 `Ordered`.
pub proof fn lemma_ordered_format_spec_invariants()
    ensures
        ORDERED_FMT().safe_inv(),
        ORDERED_FMT().productive_inv(),
        ORDERED_FMT().sound_inv(),
        ORDERED_FMT().nonmal_inv(),
        ORDERED_FMT().serialize_inv(),
        ORDERED_FMT().serialize_dps_inv(),
        ORDERED_FMT().unambiguous(),
        ORDERED_FMT().equiv_general_inv(),
        ORDERED_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(ORDERED_FMT().safe_inv());
    assert(ORDERED_FMT().productive_inv());
    assert(ORDERED_FMT().sound_inv());
    assert(ORDERED_FMT().nonmal_inv());
    assert(ORDERED_FMT().serialize_inv());
    assert(ORDERED_FMT().serialize_dps_inv());
    assert(ORDERED_FMT().unambiguous());
    assert(ORDERED_FMT().equiv_general_inv());
    assert(ORDERED_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Ordered`.
pub proof fn lemma_ordered_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <OrderedFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&ORDERED_FMT()),
        <OrderedFmt as vest_lib2::core::exec::serializer::Serializer<Output, Ordered<'i>>>::exec_inv(&ORDERED_FMT()),
        <OrderedFmt as vest_lib2::core::exec::serializer::Prepare<Ordered<'i>>>::exec_inv(&ORDERED_FMT()),
        <OrderedFmt as vest_lib2::core::exec::serializer::ByteLen<Ordered<'i>>>::exec_inv(&ORDERED_FMT()),
{
    lemma_ordered_format_spec_invariants();
    assert(<OrderedFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&ORDERED_FMT()));
    assert(<OrderedFmt as vest_lib2::core::exec::serializer::Serializer<Output, Ordered<'i>>>::exec_inv(&ORDERED_FMT()));
    assert(<OrderedFmt as vest_lib2::core::exec::serializer::Prepare<Ordered<'i>>>::exec_inv(&ORDERED_FMT()));
    assert(<OrderedFmt as vest_lib2::core::exec::serializer::ByteLen<Ordered<'i>>>::exec_inv(&ORDERED_FMT()));
}

/// Pure specification certificate for ASN.1 `Outer`.
/// BER accepts non-canonical encodings, so `sound_inv` and `nonmal_inv` do not apply.
pub proof fn lemma_outer_format_spec_invariants()
    ensures
        OUTER_FMT().safe_inv(),
        OUTER_FMT().productive_inv(),
        OUTER_FMT().serialize_inv(),
        OUTER_FMT().serialize_dps_inv(),
        OUTER_FMT().unambiguous(),
        OUTER_FMT().equiv_general_inv(),
        OUTER_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    lemma_canonical_format_spec_invariants();
    lemma_ordered_format_spec_invariants();
    lemma_shared_format_spec_invariants();
    assert(OUTER_FMT().safe_inv());
    assert(OUTER_FMT().productive_inv());
    assert(OUTER_FMT().serialize_inv());
    assert(OUTER_FMT().serialize_dps_inv());
    assert(OUTER_FMT().unambiguous());
    assert(OUTER_FMT().equiv_general_inv());
    assert(OUTER_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `Outer`.
pub proof fn lemma_outer_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <OuterFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&OUTER_FMT()),
        <OuterFmt as vest_lib2::core::exec::serializer::Serializer<Output, Outer<'i>>>::exec_inv(&OUTER_FMT()),
        <OuterFmt as vest_lib2::core::exec::serializer::Prepare<Outer<'i>>>::exec_inv(&OUTER_FMT()),
        <OuterFmt as vest_lib2::core::exec::serializer::ByteLen<Outer<'i>>>::exec_inv(&OUTER_FMT()),
{
    lemma_outer_format_spec_invariants();
    lemma_canonical_format_spec_invariants();
    lemma_canonical_format_exec_invariants::<Output>();
    lemma_ordered_format_spec_invariants();
    lemma_ordered_format_exec_invariants::<Output>();
    lemma_shared_format_spec_invariants();
    lemma_shared_format_exec_invariants::<Output>();
    assert(<OuterFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&OUTER_FMT()));
    assert(<OuterFmt as vest_lib2::core::exec::serializer::Serializer<Output, Outer<'i>>>::exec_inv(&OUTER_FMT()));
    assert(<OuterFmt as vest_lib2::core::exec::serializer::Prepare<Outer<'i>>>::exec_inv(&OUTER_FMT()));
    assert(<OuterFmt as vest_lib2::core::exec::serializer::ByteLen<Outer<'i>>>::exec_inv(&OUTER_FMT()));
}

/// Pure specification certificate for ASN.1 `NumericLabel`.
/// BER accepts non-canonical encodings, so `sound_inv` and `nonmal_inv` do not apply.
pub proof fn lemma_numeric_label_format_spec_invariants()
    ensures
        NUMERIC_LABEL_FMT().safe_inv(),
        NUMERIC_LABEL_FMT().productive_inv(),
        NUMERIC_LABEL_FMT().serialize_inv(),
        NUMERIC_LABEL_FMT().serialize_dps_inv(),
        NUMERIC_LABEL_FMT().unambiguous(),
        NUMERIC_LABEL_FMT().equiv_general_inv(),
        NUMERIC_LABEL_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(NUMERIC_LABEL_FMT().safe_inv());
    assert(NUMERIC_LABEL_FMT().productive_inv());
    assert(NUMERIC_LABEL_FMT().serialize_inv());
    assert(NUMERIC_LABEL_FMT().serialize_dps_inv());
    assert(NUMERIC_LABEL_FMT().unambiguous());
    assert(NUMERIC_LABEL_FMT().equiv_general_inv());
    assert(NUMERIC_LABEL_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `NumericLabel`.
pub proof fn lemma_numeric_label_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <NumericLabelFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&NUMERIC_LABEL_FMT()),
        <NumericLabelFmt as vest_lib2::core::exec::serializer::Serializer<Output, NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()),
        <NumericLabelFmt as vest_lib2::core::exec::serializer::Prepare<NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()),
        <NumericLabelFmt as vest_lib2::core::exec::serializer::ByteLen<NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()),
{
    lemma_numeric_label_format_spec_invariants();
    assert(<NumericLabelFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&NUMERIC_LABEL_FMT()));
    assert(<NumericLabelFmt as vest_lib2::core::exec::serializer::Serializer<Output, NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()));
    assert(<NumericLabelFmt as vest_lib2::core::exec::serializer::Prepare<NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()));
    assert(<NumericLabelFmt as vest_lib2::core::exec::serializer::ByteLen<NumericLabel>>::exec_inv(&NUMERIC_LABEL_FMT()));
}

/// Pure specification certificate for ASN.1 `UniversalLabel`.
/// BER accepts non-canonical encodings, so `sound_inv` and `nonmal_inv` do not apply.
pub proof fn lemma_universal_label_format_spec_invariants()
    ensures
        UNIVERSAL_LABEL_FMT().safe_inv(),
        UNIVERSAL_LABEL_FMT().productive_inv(),
        UNIVERSAL_LABEL_FMT().serialize_inv(),
        UNIVERSAL_LABEL_FMT().serialize_dps_inv(),
        UNIVERSAL_LABEL_FMT().unambiguous(),
        UNIVERSAL_LABEL_FMT().equiv_general_inv(),
        UNIVERSAL_LABEL_FMT().equiv_inv(),
{
    use vest_lib2::core::proof::*;
    use vest_lib2::asn1::disjoint::asn1_disjointness_lemmas;
    use vest_lib2::asn1::tag::lemma_tag_wf_implies_tag_consistent;
    use vest_lib2::combinators::disjoint::disjointness_lemmas;
    broadcast use disjointness_lemmas;
    broadcast use lemma_tag_wf_implies_tag_consistent;
    broadcast use asn1_disjointness_lemmas;
    assert(UNIVERSAL_LABEL_FMT().safe_inv());
    assert(UNIVERSAL_LABEL_FMT().productive_inv());
    assert(UNIVERSAL_LABEL_FMT().serialize_inv());
    assert(UNIVERSAL_LABEL_FMT().serialize_dps_inv());
    assert(UNIVERSAL_LABEL_FMT().unambiguous());
    assert(UNIVERSAL_LABEL_FMT().equiv_general_inv());
    assert(UNIVERSAL_LABEL_FMT().equiv_inv());
}

/// Executable API certificate for ASN.1 `UniversalLabel`.
pub proof fn lemma_universal_label_format_exec_invariants<'i, Output>()
    where
        Output: vest_lib2::core::exec::output::OutputBuf,
    ensures
        <UniversalLabelFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&UNIVERSAL_LABEL_FMT()),
        <UniversalLabelFmt as vest_lib2::core::exec::serializer::Serializer<Output, UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()),
        <UniversalLabelFmt as vest_lib2::core::exec::serializer::Prepare<UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()),
        <UniversalLabelFmt as vest_lib2::core::exec::serializer::ByteLen<UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()),
{
    lemma_universal_label_format_spec_invariants();
    assert(<UniversalLabelFmt as vest_lib2::core::exec::parser::Parser<&'i [u8]>>::exec_inv(&UNIVERSAL_LABEL_FMT()));
    assert(<UniversalLabelFmt as vest_lib2::core::exec::serializer::Serializer<Output, UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()));
    assert(<UniversalLabelFmt as vest_lib2::core::exec::serializer::Prepare<UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()));
    assert(<UniversalLabelFmt as vest_lib2::core::exec::serializer::ByteLen<UniversalLabel>>::exec_inv(&UNIVERSAL_LABEL_FMT()));
}


} // verus!
