// @generated by vestasn1 from ASN.1 module `BerFixture`.
// Generated formats parse and serialize BER.
#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use vest_lib2::asn1::*;
use vest_lib2::asn1::der_ord::{DerOrd, DerState};
use vest_lib2::asn1::disjoint::HasAsn1Start;
use vest_lib2::asn1::ber::{AnyTlvFmt, BitStringTlvFmt, BmpStringTlvFmt, BoolTlvFmt, DefaultFmt, Enumerated16TlvFmt, EnumeratedTlvFmt, Explicit, ExplicitFmt, GeneralizedTimeTlvFmt, Ia5StringTlvFmt, Implicit, ImplicitFmt, Integer16TlvFmt, Integer8TlvFmt, IntegerTlvFmt, NullTlvFmt, ObjectIdentifierTlvFmt, OctetStringTlvFmt, NumericStringTlvFmt, PrintableStringTlvFmt, RealTlvFmt, SequenceFmt, SequenceOfFmt, SetOfTlvFmt, TeletexStringTlvFmt, UniversalStringTlvFmt, UtcTimeTlvFmt, Utf8StringTlvFmt, ANY, BIT_STRING, BMP_STRING, BOOLEAN, CHOICE, DEFAULT, ENUMERATED, ENUMERATED16, EXPLICIT, EXPLICIT_APPLICATION, EXPLICIT_PRIVATE, GENERALIZED_TIME, IA5_STRING, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, INTEGER, INTEGER16, INTEGER8, NULL, NUMERIC_STRING, OBJECT_IDENTIFIER, OCTET_STRING, OPTIONAL, PRINTABLE_STRING, REAL, REQUIRED, SEQUENCE, SEQUENCE_OF, SET_OF, TELETEX_STRING, UNIVERSAL_STRING, UTC_TIME, UTF8_STRING};
use vest_lib2::asn1::ber::{BerEndFmt, BER_END};
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::combinators::Eof;
use Sum::Inl as L;
use Sum::Inr as R;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::exec::output::OutputBuf;
use vest_lib2::core::exec::parser::{PResult, Parser};
use vest_lib2::core::exec::serializer::{ByteLen, PreSerializeError, Prepare, Serializer};
use vest_lib2::core::proof::*;
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Payload = Vec<u8>;
pub type PayloadSpec = Seq<u8>;

pub type Bits = vest_lib2::asn1::BitStringOwned;
pub type BitsSpec = vest_lib2::asn1::BitStringSpec;

pub type Label = String;
pub type LabelSpec = Seq<char>;

pub type Printable = vest_lib2::asn1::PrintableStringOwned;
pub type PrintableSpec = vest_lib2::asn1::PrintableStringSpec;

pub type Ascii = vest_lib2::asn1::Ia5StringOwned;
pub type AsciiSpec = vest_lib2::asn1::Ia5StringSpec;

pub type Legacy = vest_lib2::asn1::TeletexStringOwned;
pub type LegacySpec = vest_lib2::asn1::TeletexStringSpec;

pub type Wide = vest_lib2::asn1::BmpString;
pub type WideSpec = vest_lib2::asn1::BmpStringSpec;

pub type OpenValue = vest_lib2::asn1::AnyOwned;
pub type OpenValueSpec = vest_lib2::asn1::AnySpec;

/// Value type for ASN.1 `Item`.
pub struct Item {
    pub payload: Payload,
    pub bits: Bits,
    pub label: Label,
    pub printable: Option<Printable>,
    pub open: Option<OpenValue>,
}

#[verifier::ext_equal]
pub struct ItemSpec<T0 = PayloadSpec, T1 = BitsSpec, T2 = LabelSpec, T3 = Option<PrintableSpec>, T4 = Option<OpenValueSpec>> {
    pub payload: T0,
    pub bits: T1,
    pub label: T2,
    pub printable: T3,
    pub open: T4,
}

impl DeepView for Item {
    type V = ItemSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        ItemSpec {
            payload: self.payload.deep_view(),
            bits: self.bits.deep_view(),
            label: self.label.deep_view(),
            printable: self.printable.deep_view(),
            open: self.open.deep_view(),
        }
    }
}

/// Value type for ASN.1 `AutomationChoice`.
pub enum AutomationChoice {
    BooleanValue(bool),
    OctetsValue(Vec<u8>),
    BitsValue(vest_lib2::asn1::BitStringOwned),
    TextValue(String),
    PrintableValue(vest_lib2::asn1::PrintableStringOwned),
    OpenValue(vest_lib2::asn1::AnyOwned),
}

#[verifier::ext_equal]
pub enum AutomationChoiceSpec<T0 = bool, T1 = Seq<u8>, T2 = vest_lib2::asn1::BitStringSpec, T3 = Seq<char>, T4 = vest_lib2::asn1::PrintableStringSpec, T5 = vest_lib2::asn1::AnySpec> {
    BooleanValue(T0),
    OctetsValue(T1),
    BitsValue(T2),
    TextValue(T3),
    PrintableValue(T4),
    OpenValue(T5),
}

impl DeepView for AutomationChoice {
    type V = AutomationChoiceSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        match self {
            AutomationChoice::BooleanValue(value) => AutomationChoiceSpec::BooleanValue(value.deep_view()),
            AutomationChoice::OctetsValue(value) => AutomationChoiceSpec::OctetsValue(value.deep_view()),
            AutomationChoice::BitsValue(value) => AutomationChoiceSpec::BitsValue(value.deep_view()),
            AutomationChoice::TextValue(value) => AutomationChoiceSpec::TextValue(value.deep_view()),
            AutomationChoice::PrintableValue(value) => AutomationChoiceSpec::PrintableValue(value.deep_view()),
            AutomationChoice::OpenValue(value) => AutomationChoiceSpec::OpenValue(value.deep_view()),
        }
    }
}

/// Value type for ASN.1 `AutomationSequence`.
pub struct AutomationSequence {
    pub prefix: Option<bool>,
    pub enabled: bool,
    pub payload: Option<Vec<u8>>,
    pub marker: bool,
    pub selected: Option<AutomationChoice>,
}

#[verifier::ext_equal]
pub struct AutomationSequenceSpec<T0 = Option<bool>, T1 = bool, T2 = Option<Seq<u8>>, T3 = bool, T4 = Option<AutomationChoiceSpec>> {
    pub prefix: T0,
    pub enabled: T1,
    pub payload: T2,
    pub marker: T3,
    pub selected: T4,
}

impl DeepView for AutomationSequence {
    type V = AutomationSequenceSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        AutomationSequenceSpec {
            prefix: self.prefix.deep_view(),
            enabled: self.enabled.deep_view(),
            payload: self.payload.deep_view(),
            marker: self.marker.deep_view(),
            selected: self.selected.deep_view(),
        }
    }
}

pub type Items = Vec<Item>;
pub type ItemsSpec = Seq<ItemSpec>;

pub type Flags = Vec<bool>;
pub type FlagsSpec = Seq<bool>;

pub type FlagSet = Vec<bool>;
pub type FlagSetSpec = Seq<bool>;

#[derive(Clone, Copy)]
pub struct ItemForward;
#[derive(Clone, Copy)]
pub struct ItemReverse;

impl<T0, T1, T2, T3, T4> ItemSpec<T0, T1, T2, T3, T4> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, (T2, (T3, (T4, ())))))) -> Self {
        let (payload, (bits, (label, (printable, (open, _end))))) = input;
        Self {
            payload,
            bits,
            label,
            printable,
            open,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, (T2, (T3, (T4, ()))))) {
        (self.payload, (self.bits, (self.label, (self.printable, (self.open, ())))))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(ItemSpec::from_structural);
        reveal(ItemSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, (T2, (T3, (T4, ()))))))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(ItemSpec::from_structural);
        reveal(ItemSpec::into_structural);
    }
}

impl SpecMap for ItemForward {
    type Input = (PayloadSpec, (BitsSpec, (LabelSpec, (Option<PrintableSpec>, (Option<OpenValueSpec>, ())))));
    type Output = ItemSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        ItemSpec::from_structural(input)
    }
}

impl SpecMap for ItemReverse {
    type Input = ItemSpec;
    type Output = (PayloadSpec, (BitsSpec, (LabelSpec, (Option<PrintableSpec>, (Option<OpenValueSpec>, ())))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl Map<(Payload, (Bits, (Label, (Option<Printable>, (Option<OpenValue>, ())))))> for ItemForward {
    type O = Item;
    fn map(&self, input: (Payload, (Bits, (Label, (Option<Printable>, (Option<OpenValue>, ())))))) -> (value: Self::O) {
        proof {
            reveal(<Item as DeepView>::deep_view);
            reveal(ItemSpec::from_structural);
        }
        let (payload, (bits, (label, (printable, (open, _end))))) = input;
        Item {
            payload,
            bits,
            label,
            printable,
            open,
        }
    }
}

impl<'x> Map<&'x Item> for ItemReverse {
    type O = (&'x Payload, (&'x Bits, (&'x Label, (Option<&'x Printable>, (Option<&'x OpenValue>, ())))));
    fn map(&self, value: &'x Item) -> (output: Self::O) {
        proof {
            reveal(<Item as DeepView>::deep_view);
            reveal(ItemSpec::into_structural);
        }
        (&value.payload, (&value.bits, (&value.label, (value.printable.as_ref(), (value.open.as_ref(), ())))))
    }
}

#[derive(Clone, Copy)]
pub struct AutomationChoiceForward;
#[derive(Clone, Copy)]
pub struct AutomationChoiceReverse;

impl<T0, T1, T2, T3, T4, T5> AutomationChoiceSpec<T0, T1, T2, T3, T4, T5> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: Sum<Sum<T0, T1>, Sum<Sum<T2, T3>, Sum<T4, T5>>>) -> Self {
        match input {
            L(L(value)) => Self::BooleanValue(value),
            L(R(value)) => Self::OctetsValue(value),
            R(L(L(value))) => Self::BitsValue(value),
            R(L(R(value))) => Self::TextValue(value),
            R(R(L(value))) => Self::PrintableValue(value),
            R(R(R(value))) => Self::OpenValue(value),
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> Sum<Sum<T0, T1>, Sum<Sum<T2, T3>, Sum<T4, T5>>> {
        match self {
            Self::BooleanValue(value) => L(L(value)),
            Self::OctetsValue(value) => L(R(value)),
            Self::BitsValue(value) => R(L(L(value))),
            Self::TextValue(value) => R(L(R(value))),
            Self::PrintableValue(value) => R(R(L(value))),
            Self::OpenValue(value) => R(R(R(value))),
        }
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(AutomationChoiceSpec::from_structural);
        reveal(AutomationChoiceSpec::into_structural);
        match self {
            Self::BooleanValue(_) => {},
            Self::OctetsValue(_) => {},
            Self::BitsValue(_) => {},
            Self::TextValue(_) => {},
            Self::PrintableValue(_) => {},
            Self::OpenValue(_) => {},
        }
    }

    pub proof fn lemma_into_from(input: Sum<Sum<T0, T1>, Sum<Sum<T2, T3>, Sum<T4, T5>>>)
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(AutomationChoiceSpec::from_structural);
        reveal(AutomationChoiceSpec::into_structural);
        match input {
            L(L(_)) => {},
            L(R(_)) => {},
            R(L(L(_))) => {},
            R(L(R(_))) => {},
            R(R(L(_))) => {},
            R(R(R(_))) => {},
        }
    }
}

impl SpecMap for AutomationChoiceForward {
    type Input = Sum<Sum<bool, Seq<u8>>, Sum<Sum<vest_lib2::asn1::BitStringSpec, Seq<char>>, Sum<vest_lib2::asn1::PrintableStringSpec, vest_lib2::asn1::AnySpec>>>;
    type Output = AutomationChoiceSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        AutomationChoiceSpec::from_structural(input)
    }
}

impl SpecMap for AutomationChoiceReverse {
    type Input = AutomationChoiceSpec;
    type Output = Sum<Sum<bool, Seq<u8>>, Sum<Sum<vest_lib2::asn1::BitStringSpec, Seq<char>>, Sum<vest_lib2::asn1::PrintableStringSpec, vest_lib2::asn1::AnySpec>>>;
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl Map<Sum<Sum<bool, Vec<u8>>, Sum<Sum<vest_lib2::asn1::BitStringOwned, String>, Sum<vest_lib2::asn1::PrintableStringOwned, vest_lib2::asn1::AnyOwned>>>> for AutomationChoiceForward {
    type O = AutomationChoice;
    fn map(&self, input: Sum<Sum<bool, Vec<u8>>, Sum<Sum<vest_lib2::asn1::BitStringOwned, String>, Sum<vest_lib2::asn1::PrintableStringOwned, vest_lib2::asn1::AnyOwned>>>) -> (value: Self::O) {
        proof {
            reveal(<AutomationChoice as DeepView>::deep_view);
            reveal(AutomationChoiceSpec::from_structural);
        }
        match input {
            L(L(value)) => AutomationChoice::BooleanValue(value),
            L(R(value)) => AutomationChoice::OctetsValue(value),
            R(L(L(value))) => AutomationChoice::BitsValue(value),
            R(L(R(value))) => AutomationChoice::TextValue(value),
            R(R(L(value))) => AutomationChoice::PrintableValue(value),
            R(R(R(value))) => AutomationChoice::OpenValue(value),
        }
    }
}

impl<'x> Map<&'x AutomationChoice> for AutomationChoiceReverse {
    type O = Sum<Sum<&'x bool, &'x Vec<u8>>, Sum<Sum<&'x vest_lib2::asn1::BitStringOwned, &'x String>, Sum<&'x vest_lib2::asn1::PrintableStringOwned, &'x vest_lib2::asn1::AnyOwned>>>;
    fn map(&self, value: &'x AutomationChoice) -> (output: Self::O) {
        proof {
            reveal(<AutomationChoice as DeepView>::deep_view);
            reveal(AutomationChoiceSpec::into_structural);
        }
        match value {
            AutomationChoice::BooleanValue(value) => L(L(value)),
            AutomationChoice::OctetsValue(value) => L(R(value)),
            AutomationChoice::BitsValue(value) => R(L(L(value))),
            AutomationChoice::TextValue(value) => R(L(R(value))),
            AutomationChoice::PrintableValue(value) => R(R(L(value))),
            AutomationChoice::OpenValue(value) => R(R(R(value))),
        }
    }
}

#[derive(Clone, Copy)]
pub struct AutomationSequenceForward;
#[derive(Clone, Copy)]
pub struct AutomationSequenceReverse;

impl<T0, T1, T2, T3, T4> AutomationSequenceSpec<T0, T1, T2, T3, T4> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, (T2, (T3, (T4, ())))))) -> Self {
        let (prefix, (enabled, (payload, (marker, (selected, _end))))) = input;
        Self {
            prefix,
            enabled,
            payload,
            marker,
            selected,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, (T2, (T3, (T4, ()))))) {
        (self.prefix, (self.enabled, (self.payload, (self.marker, (self.selected, ())))))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(AutomationSequenceSpec::from_structural);
        reveal(AutomationSequenceSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, (T2, (T3, (T4, ()))))))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(AutomationSequenceSpec::from_structural);
        reveal(AutomationSequenceSpec::into_structural);
    }
}

impl SpecMap for AutomationSequenceForward {
    type Input = (Option<bool>, (bool, (Option<Seq<u8>>, (bool, (Option<AutomationChoiceSpec>, ())))));
    type Output = AutomationSequenceSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        AutomationSequenceSpec::from_structural(input)
    }
}

impl SpecMap for AutomationSequenceReverse {
    type Input = AutomationSequenceSpec;
    type Output = (Option<bool>, (bool, (Option<Seq<u8>>, (bool, (Option<AutomationChoiceSpec>, ())))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl Map<(Option<bool>, (bool, (Option<Vec<u8>>, (bool, (Option<AutomationChoice>, ())))))> for AutomationSequenceForward {
    type O = AutomationSequence;
    fn map(&self, input: (Option<bool>, (bool, (Option<Vec<u8>>, (bool, (Option<AutomationChoice>, ())))))) -> (value: Self::O) {
        proof {
            reveal(<AutomationSequence as DeepView>::deep_view);
            reveal(AutomationSequenceSpec::from_structural);
        }
        let (prefix, (enabled, (payload, (marker, (selected, _end))))) = input;
        AutomationSequence {
            prefix,
            enabled,
            payload,
            marker,
            selected,
        }
    }
}

impl<'x> Map<&'x AutomationSequence> for AutomationSequenceReverse {
    type O = (Option<&'x bool>, (bool, (Option<&'x Vec<u8>>, (&'x bool, (Option<&'x AutomationChoice>, ())))));
    fn map(&self, value: &'x AutomationSequence) -> (output: Self::O) {
        proof {
            reveal(<AutomationSequence as DeepView>::deep_view);
            reveal(AutomationSequenceSpec::into_structural);
        }
        (value.prefix.as_ref(), (value.enabled, (value.payload.as_ref(), (&value.marker, (value.selected.as_ref(), ())))))
    }
}

/// BER format for ASN.1 `Payload`.
type PAYLOAD__ = Refined<OctetStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct PAYLOAD(pub Class, pub u64);
impl PAYLOAD {
    pub const Fmt: Self = Self(Class::Universal, 4u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> PAYLOAD__
        returns
            (
                Refined(OCTET_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(OCTET_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `Bits`.
type BITS__ = BitStringTlvFmt;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct BITS(pub Class, pub u64);
impl BITS {
    pub const Fmt: Self = Self(Class::Universal, 3u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> BITS__
        returns
            (
                BIT_STRING
            ),
    {
        BIT_STRING
    }
}

/// BER format for ASN.1 `Label`.
type LABEL__ = Refined<Utf8StringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct LABEL(pub Class, pub u64);
impl LABEL {
    pub const Fmt: Self = Self(Class::Universal, 12u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> LABEL__
        returns
            (
                Refined(UTF8_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(UTF8_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `Printable`.
type PRINTABLE__ = Refined<PrintableStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct PRINTABLE(pub Class, pub u64);
impl PRINTABLE {
    pub const Fmt: Self = Self(Class::Universal, 19u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> PRINTABLE__
        returns
            (
                Refined(PRINTABLE_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(PRINTABLE_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `Ascii`.
type ASCII__ = Refined<Ia5StringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct ASCII(pub Class, pub u64);
impl ASCII {
    pub const Fmt: Self = Self(Class::Universal, 22u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> ASCII__
        returns
            (
                Refined(IA5_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(IA5_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `Legacy`.
type LEGACY__ = Refined<TeletexStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct LEGACY(pub Class, pub u64);
impl LEGACY {
    pub const Fmt: Self = Self(Class::Universal, 20u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> LEGACY__
        returns
            (
                Refined(TELETEX_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(TELETEX_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `Wide`.
type WIDE__ = Refined<BmpStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct WIDE(pub Class, pub u64);
impl WIDE {
    pub const Fmt: Self = Self(Class::Universal, 30u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> WIDE__
        returns
            (
                Refined(BMP_STRING, Size::<true, 1, true, 16>)
            ),
    {
        Refined(BMP_STRING, Size::<true, 1, true, 16>)
    }
}

/// BER format for ASN.1 `OpenValue`.
type OPEN_VALUE__ = AnyTlvFmt;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct OPEN_VALUE;
impl OPEN_VALUE {
    pub const Fmt: Self = Self;

    #[verifier::allow_in_spec]
    pub const fn schema() -> OPEN_VALUE__
        returns
            (
                ANY
            ),
    {
        ANY
    }
}

/// BER format for ASN.1 `Item`.
type ITEM__ = Mapped<SequenceFmt<Pair<Ref<PAYLOAD>, Pair<ImplicitFmt<Ref<BITS>>, Pair<ImplicitFmt<Ref<LABEL>>, Optional<ImplicitFmt<Ref<PRINTABLE>>, Optional<ExplicitFmt<Ref<OPEN_VALUE>>, BerEndFmt>>>>>>, BiMap<ItemForward, ItemReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct ITEM(pub Class, pub u64);
impl ITEM {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> ITEM__
        returns
            (
                Mapped {
                    inner:
                        SEQUENCE(
                            REQUIRED(Ref(PAYLOAD::Fmt),
                            REQUIRED(IMPLICIT(0u64, Ref(BITS::Fmt)),
                            REQUIRED(IMPLICIT(1u64, Ref(LABEL::Fmt)),
                            OPTIONAL(IMPLICIT(2u64, Ref(PRINTABLE::Fmt)),
                            OPTIONAL(EXPLICIT(3u64, Ref(OPEN_VALUE::Fmt)),
                            BER_END))))),
                        ),
                    mapper: BiMap(ItemForward, ItemReverse),
                }
            ),
    {
        Mapped {
            inner:
                SEQUENCE(
                    REQUIRED(Ref(PAYLOAD::Fmt),
                    REQUIRED(IMPLICIT(0u64, Ref(BITS::Fmt)),
                    REQUIRED(IMPLICIT(1u64, Ref(LABEL::Fmt)),
                    OPTIONAL(IMPLICIT(2u64, Ref(PRINTABLE::Fmt)),
                    OPTIONAL(EXPLICIT(3u64, Ref(OPEN_VALUE::Fmt)),
                    BER_END))))),
                ),
            mapper: BiMap(ItemForward, ItemReverse),
        }
    }
}

/// BER format for ASN.1 `AutomationChoice`.
type AUTOMATION_CHOICE__ = Mapped<Choice<Choice<ImplicitFmt<Ref<BoolTlvFmt>>, ImplicitFmt<Ref<OctetStringTlvFmt>>>, Choice<Choice<ImplicitFmt<Ref<BitStringTlvFmt>>, ImplicitFmt<Ref<Utf8StringTlvFmt>>>, Choice<ImplicitFmt<Ref<PrintableStringTlvFmt>>, ExplicitFmt<Ref<AnyTlvFmt>>>>>, BiMap<AutomationChoiceForward, AutomationChoiceReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct AUTOMATION_CHOICE;
impl AUTOMATION_CHOICE {
    pub const Fmt: Self = Self;

    #[verifier::allow_in_spec]
    pub const fn schema() -> AUTOMATION_CHOICE__
        returns
            (
                Mapped {
                    inner:
                        CHOICE(
                            CHOICE(
                                IMPLICIT(10u64, Ref(BOOLEAN)),
                                IMPLICIT(11u64, Ref(OCTET_STRING))),
                            CHOICE(
                                CHOICE(
                                    IMPLICIT(12u64, Ref(BIT_STRING)),
                                    IMPLICIT(13u64, Ref(UTF8_STRING))),
                                CHOICE(
                                    IMPLICIT(14u64, Ref(PRINTABLE_STRING)),
                                    EXPLICIT(15u64, Ref(ANY))))),
                    mapper: BiMap(AutomationChoiceForward, AutomationChoiceReverse),
                }
            ),
    {
        Mapped {
            inner:
                CHOICE(
                    CHOICE(
                        IMPLICIT(10u64, Ref(BOOLEAN)),
                        IMPLICIT(11u64, Ref(OCTET_STRING))),
                    CHOICE(
                        CHOICE(
                            IMPLICIT(12u64, Ref(BIT_STRING)),
                            IMPLICIT(13u64, Ref(UTF8_STRING))),
                        CHOICE(
                            IMPLICIT(14u64, Ref(PRINTABLE_STRING)),
                            EXPLICIT(15u64, Ref(ANY))))),
            mapper: BiMap(AutomationChoiceForward, AutomationChoiceReverse),
        }
    }
}

/// BER format for ASN.1 `AutomationSequence`.
type AUTOMATION_SEQUENCE__ = Mapped<SequenceFmt<Optional<ImplicitFmt<Ref<BoolTlvFmt>>, DefaultFmt<ImplicitFmt<BoolTlvFmt>, bool, Optional<ExplicitFmt<Ref<OctetStringTlvFmt>>, Pair<ImplicitFmt<Ref<BoolTlvFmt>>, Optional<ExplicitFmt<Ref<AUTOMATION_CHOICE>>, BerEndFmt>>>>>>, BiMap<AutomationSequenceForward, AutomationSequenceReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct AUTOMATION_SEQUENCE(pub Class, pub u64);
impl AUTOMATION_SEQUENCE {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> AUTOMATION_SEQUENCE__
        returns
            (
                Mapped {
                    inner:
                        SEQUENCE(
                            OPTIONAL(IMPLICIT(20u64, Ref(BOOLEAN)),
                            DEFAULT(IMPLICIT(21u64, BOOLEAN), true,
                            OPTIONAL(EXPLICIT(22u64, Ref(OCTET_STRING)),
                            REQUIRED(IMPLICIT(23u64, Ref(BOOLEAN)),
                            OPTIONAL(EXPLICIT(24u64, Ref(AUTOMATION_CHOICE::Fmt)),
                            BER_END))))),
                        ),
                    mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
                }
            ),
    {
        Mapped {
            inner:
                SEQUENCE(
                    OPTIONAL(IMPLICIT(20u64, Ref(BOOLEAN)),
                    DEFAULT(IMPLICIT(21u64, BOOLEAN), true,
                    OPTIONAL(EXPLICIT(22u64, Ref(OCTET_STRING)),
                    REQUIRED(IMPLICIT(23u64, Ref(BOOLEAN)),
                    OPTIONAL(EXPLICIT(24u64, Ref(AUTOMATION_CHOICE::Fmt)),
                    BER_END))))),
                ),
            mapper: BiMap(AutomationSequenceForward, AutomationSequenceReverse),
        }
    }
}

/// BER format for ASN.1 `Items`.
type ITEMS__ = SequenceOfFmt<ITEM>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct ITEMS(pub Class, pub u64);
impl ITEMS {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> ITEMS__
        returns
            (
                SEQUENCE_OF(ITEM::Fmt)
            ),
    {
        SEQUENCE_OF(ITEM::Fmt)
    }
}

/// BER format for ASN.1 `Flags`.
type FLAGS__ = SequenceOfFmt<BoolTlvFmt>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct FLAGS(pub Class, pub u64);
impl FLAGS {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> FLAGS__
        returns
            (
                SEQUENCE_OF(BOOLEAN)
            ),
    {
        SEQUENCE_OF(BOOLEAN)
    }
}

/// BER format for ASN.1 `FlagSet`.
type FLAG_SET__ = SetOfTlvFmt<BoolTlvFmt>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct FLAG_SET(pub Class, pub u64);
impl FLAG_SET {
    pub const Fmt: Self = Self(Class::Universal, 17u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> FLAG_SET__
        returns
            (
                SET_OF(BOOLEAN)
            ),
    {
        SET_OF(BOOLEAN)
    }
}


} // verus!

mod __impl_payload {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, PAYLOAD, PAYLOAD__, PayloadSpec, Payload);
}

mod __impl_bits {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, BITS, BITS__, BitsSpec, Bits);
}

mod __impl_label {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, LABEL, LABEL__, LabelSpec, Label);
}

mod __impl_printable {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, PRINTABLE, PRINTABLE__, PrintableSpec, Printable);
}

mod __impl_ascii {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, ASCII, ASCII__, AsciiSpec, Ascii);
}

mod __impl_legacy {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, LEGACY, LEGACY__, LegacySpec, Legacy);
}

mod __impl_wide {
    use super::*;

    vest_lib2::impl_ber!(tagged(false), owned, WIDE, WIDE__, WideSpec, Wide);
}

mod __impl_open_value {
    use super::*;

    vest_lib2::impl_ber!(untagged_start, owned, OPEN_VALUE, OPEN_VALUE__, OpenValueSpec, OpenValue);
}

mod __impl_item {
    use super::*;

    vest_lib2::impl_ber!(tagged(true), owned, ITEM, ITEM__, ItemSpec, Item, ItemForward, ItemReverse);
}

mod __impl_automation_choice {
    use super::*;

    vest_lib2::impl_ber!(untagged, owned, AUTOMATION_CHOICE, AUTOMATION_CHOICE__, AutomationChoiceSpec, AutomationChoice, AutomationChoiceForward, AutomationChoiceReverse);
}

mod __impl_automation_sequence {
    use super::*;

    vest_lib2::impl_ber!(tagged(true), owned, AUTOMATION_SEQUENCE, AUTOMATION_SEQUENCE__, AutomationSequenceSpec, AutomationSequence, AutomationSequenceForward, AutomationSequenceReverse);
}

mod __impl_items {
    use super::*;

    vest_lib2::impl_ber!(tagged(true), owned, ITEMS, ITEMS__, ItemsSpec, Items);
}

mod __impl_flags {
    use super::*;

    vest_lib2::impl_ber!(tagged(true), owned, FLAGS, FLAGS__, FlagsSpec, Flags);
}

mod __impl_flag_set {
    use super::*;

    vest_lib2::impl_ber!(tagged(true), owned, FLAG_SET, FLAG_SET__, FlagSetSpec, FlagSet);
}
