[package]
name = "vps-cbor-runtime-eval"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vest_lib2 = { path = "../../../vest_lib2" }
ciborium = "0.2.2"
cbor4ii = { version = "1.2.2", features = ["serde1"] }
minicbor-serde = { version = "0.7.1", features = ["std"] }
serde = "1"
serde_json = "1"
criterion = "0.5"

[[bench]]
name = "generic_cbor"
harness = false

[[bench]]
name = "real_cose"
harness = false

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1
