[package]
name = "vest_asn1"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
description = "Generate verified Vest parsers and serializers from ASN.1 schemas"
repository.workspace = true

[dependencies]
synta-codegen = { path = "vendor/synta-codegen" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(verus_only)", "cfg(verus_keep_ghost)"] }
