// @generated by vestasn1 from ASN.1 module `MixedFixture`.
// Generated formats parse and serialize a schema-selected mixture of BER and DER.
#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use vest_lib2::asn1::*;
use vest_lib2::asn1::der_ord::{DerOrd, DerState};
#[cfg(verus_only)]
use vest_lib2::asn1::disjoint::{asn1_start_any_non_eoc, asn1_start_ber_boundary, asn1_start_empty, asn1_start_exact_uint, asn1_start_identity_uint, asn1_start_mask, asn1_start_union, asn1_starts_disjoint, lemma_asn1_start_exact_uint, lemma_asn1_start_identity_uint, lemma_disjoint_asn1_starts, HasAsn1Start};
use vest_lib2::asn1::tag::tag_num_from_uint;
use vest_lib2::asn1::modifiers::{implicitly_tagged as Implicit, ImplicitFmt, CHOICE, IMPLICIT, IMPLICIT_APPLICATION, IMPLICIT_PRIVATE, OPTIONAL, REQUIRED};
use vest_lib2::combinators::mapped::spec::{BiMap, SpecMap};
use vest_lib2::combinators::*;
use vest_lib2::combinators::Eof;
use Sum::Inl as L;
use Sum::Inr as R;
use vest_lib2::core::exec::fns::{Map, Pred};
use vest_lib2::core::exec::output::OutputBuf;
use vest_lib2::core::exec::parser::{PResult, Parser};
use vest_lib2::core::exec::serializer::{ByteLen, PreSerializeError, Prepare, Serializer};
use vest_lib2::core::proof::*;
use vest_lib2::core::spec::*;
use vstd::prelude::*;

verus! {

pub type Version = i8;
pub type VersionSpec = i8;

/// Value type for ASN.1 `Shared`.
pub struct Shared<'a> {
    pub version: Version,
    pub payload: &'a [u8],
}

#[verifier::ext_equal]
pub struct SharedSpec<T0 = VersionSpec, T1 = Seq<u8>> {
    pub version: T0,
    pub payload: T1,
}

impl<'a> DeepView for Shared<'a> {
    type V = SharedSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        SharedSpec {
            version: self.version.deep_view(),
            payload: self.payload.deep_view(),
        }
    }
}

pub type Canonical<'a> = Vec<Shared<'a>>;
pub type CanonicalSpec = Seq<SharedSpec>;

/// Value type for ASN.1 `Ordered`.
pub struct Ordered<'a> {
    pub first: bool,
    pub second: Option<vest_lib2::asn1::Integer<'a>>,
}

#[verifier::ext_equal]
pub struct OrderedSpec<T0 = bool, T1 = Option<int>> {
    pub first: T0,
    pub second: T1,
}

impl<'a> DeepView for Ordered<'a> {
    type V = OrderedSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        OrderedSpec {
            first: self.first.deep_view(),
            second: self.second.deep_view(),
        }
    }
}

/// Value type for ASN.1 `Outer`.
pub struct Outer<'a> {
    pub shared: Shared<'a>,
    pub canonical: Canonical<'a>,
    pub ordered: Ordered<'a>,
    pub trailing: Option<vest_lib2::asn1::AnyOwned>,
}

#[verifier::ext_equal]
pub struct OuterSpec<T0 = SharedSpec, T1 = CanonicalSpec, T2 = OrderedSpec, T3 = Option<vest_lib2::asn1::AnySpec>> {
    pub shared: T0,
    pub canonical: T1,
    pub ordered: T2,
    pub trailing: T3,
}

impl<'a> DeepView for Outer<'a> {
    type V = OuterSpec;
    #[verifier::opaque]
    open spec fn deep_view(&self) -> Self::V {
        OuterSpec {
            shared: self.shared.deep_view(),
            canonical: self.canonical.deep_view(),
            ordered: self.ordered.deep_view(),
            trailing: self.trailing.deep_view(),
        }
    }
}

pub type NumericLabel = vest_lib2::asn1::NumericStringOwned;
pub type NumericLabelSpec = vest_lib2::asn1::NumericStringSpec;

pub type UniversalLabel = vest_lib2::asn1::UniversalString;
pub type UniversalLabelSpec = vest_lib2::asn1::UniversalStringSpec;

#[derive(Clone, Copy)]
pub struct SharedForward;
#[derive(Clone, Copy)]
pub struct SharedReverse;

impl<T0, T1> SharedSpec<T0, T1> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, ()))) -> Self {
        let (version, (payload, _end)) = input;
        Self {
            version,
            payload,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, ())) {
        (self.version, (self.payload, ()))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(SharedSpec::from_structural);
        reveal(SharedSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, ())))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(SharedSpec::from_structural);
        reveal(SharedSpec::into_structural);
    }
}

impl SpecMap for SharedForward {
    type Input = (VersionSpec, (Seq<u8>, ()));
    type Output = SharedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        SharedSpec::from_structural(input)
    }
}

impl SpecMap for SharedReverse {
    type Input = SharedSpec;
    type Output = (VersionSpec, (Seq<u8>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl<'a> Map<(Version, (&'a [u8], ()))> for SharedForward {
    type O = Shared<'a>;
    fn map(&self, input: (Version, (&'a [u8], ()))) -> (value: Self::O) {
        proof {
            reveal(<Shared as DeepView>::deep_view);
            reveal(SharedSpec::from_structural);
        }
        let (version, (payload, _end)) = input;
        Shared {
            version,
            payload,
        }
    }
}

impl<'a, 'x> Map<&'x Shared<'a>> for SharedReverse {
    type O = (Version, (&'x &'a [u8], ()));
    fn map(&self, value: &'x Shared<'a>) -> (output: Self::O) {
        proof {
            reveal(<Shared as DeepView>::deep_view);
            reveal(SharedSpec::into_structural);
        }
        let result = (value.version, (&value.payload, ()));
        proof {
            assert(result.deep_view() == value.deep_view().into_structural());
        }
        result
    }
}

#[derive(Clone, Copy)]
pub struct OrderedForward;
#[derive(Clone, Copy)]
pub struct OrderedReverse;

impl<T0, T1> OrderedSpec<T0, T1> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, ()))) -> Self {
        let (first, (second, _end)) = input;
        Self {
            first,
            second,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, ())) {
        (self.first, (self.second, ()))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(OrderedSpec::from_structural);
        reveal(OrderedSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, ())))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(OrderedSpec::from_structural);
        reveal(OrderedSpec::into_structural);
    }
}

impl SpecMap for OrderedForward {
    type Input = (bool, (Option<int>, ()));
    type Output = OrderedSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        OrderedSpec::from_structural(input)
    }
}

impl SpecMap for OrderedReverse {
    type Input = OrderedSpec;
    type Output = (bool, (Option<int>, ()));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl<'a> Map<(bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))> for OrderedForward {
    type O = Ordered<'a>;
    fn map(&self, input: (bool, (Option<vest_lib2::asn1::Integer<'a>>, ()))) -> (value: Self::O) {
        proof {
            reveal(<Ordered as DeepView>::deep_view);
            reveal(OrderedSpec::from_structural);
        }
        let (first, (second, _end)) = input;
        Ordered {
            first,
            second,
        }
    }
}

impl<'a, 'x> Map<&'x Ordered<'a>> for OrderedReverse {
    type O = (&'x bool, (Option<&'x vest_lib2::asn1::Integer<'a>>, ()));
    fn map(&self, value: &'x Ordered<'a>) -> (output: Self::O) {
        proof {
            reveal(<Ordered as DeepView>::deep_view);
            reveal(OrderedSpec::into_structural);
        }
        let result = (&value.first, (value.second.as_ref(), ()));
        proof {
            assert(result.deep_view() == value.deep_view().into_structural());
        }
        result
    }
}

#[derive(Clone, Copy)]
pub struct OuterForward;
#[derive(Clone, Copy)]
pub struct OuterReverse;

impl<T0, T1, T2, T3> OuterSpec<T0, T1, T2, T3> {
    #[verifier::opaque]
    pub open spec fn from_structural(input: (T0, (T1, (T2, (T3, ()))))) -> Self {
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        Self {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }

    #[verifier::opaque]
    pub open spec fn into_structural(self) -> (T0, (T1, (T2, (T3, ())))) {
        (self.shared, (self.canonical, (self.ordered, (self.trailing, ()))))
    }

    pub proof fn lemma_from_into(self)
        ensures Self::from_structural(Self::into_structural(self)) == self,
    {
        reveal(OuterSpec::from_structural);
        reveal(OuterSpec::into_structural);
    }

    pub proof fn lemma_into_from(input: (T0, (T1, (T2, (T3, ())))))
        ensures Self::into_structural(Self::from_structural(input)) == input,
    {
        reveal(OuterSpec::from_structural);
        reveal(OuterSpec::into_structural);
    }
}

impl SpecMap for OuterForward {
    type Input = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    type Output = OuterSpec;
    open spec fn spec_map(&self, input: Self::Input) -> Self::Output {
        OuterSpec::from_structural(input)
    }
}

impl SpecMap for OuterReverse {
    type Input = OuterSpec;
    type Output = (SharedSpec, (CanonicalSpec, (OrderedSpec, (Option<vest_lib2::asn1::AnySpec>, ()))));
    open spec fn spec_map(&self, value: Self::Input) -> Self::Output {
        value.into_structural()
    }
}

impl<'a> Map<(Shared<'a>, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))> for OuterForward {
    type O = Outer<'a>;
    fn map(&self, input: (Shared<'a>, (Canonical<'a>, (Ordered<'a>, (Option<vest_lib2::asn1::AnyOwned>, ()))))) -> (value: Self::O) {
        proof {
            reveal(<Outer as DeepView>::deep_view);
            reveal(OuterSpec::from_structural);
        }
        let (shared, (canonical, (ordered, (trailing, _end)))) = input;
        Outer {
            shared,
            canonical,
            ordered,
            trailing,
        }
    }
}

impl<'a, 'x> Map<&'x Outer<'a>> for OuterReverse {
    type O = (&'x Shared<'a>, (&'x Canonical<'a>, (&'x Ordered<'a>, (Option<&'x vest_lib2::asn1::AnyOwned>, ()))));
    fn map(&self, value: &'x Outer<'a>) -> (output: Self::O) {
        proof {
            reveal(<Outer as DeepView>::deep_view);
            reveal(OuterSpec::into_structural);
        }
        let result = (&value.shared, (&value.canonical, (&value.ordered, (value.trailing.as_ref(), ()))));
        proof {
            assert(result.deep_view() == value.deep_view().into_structural());
        }
        result
    }
}

/// DER format for ASN.1 `Version`.
type VERSION__ = Refined<vest_lib2::asn1::der::Integer8TlvFmt, IntegerRange<true, 0, true, 1>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct VERSION(pub Class, pub u64);
impl VERSION {
    pub const Fmt: Self = Self(Class::Universal, 2u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> VERSION__
        returns
            ({
                use vest_lib2::asn1::der::INTEGER8;
                Refined(INTEGER8, IntegerRange::<true, 0, true, 1>)
            }),
    {
        use vest_lib2::asn1::der::INTEGER8;
        Refined(INTEGER8, IntegerRange::<true, 0, true, 1>)
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0000000000000004u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(VERSION::spec_inner);
        lemma_asn1_start_exact_uint(self.0, false, self.1);
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0000000000000004u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// DER format for ASN.1 `Shared`.
type SHARED__ = Mapped<vest_lib2::asn1::der::SequenceFmt<vest_lib2::asn1::der::DefaultFmt<VERSION, i8, Pair<Ref<vest_lib2::asn1::der::OctetStringTlvFmt>, Eof>>>, BiMap<SharedForward, SharedReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct SHARED(pub Class, pub u64);
impl SHARED {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> SHARED__
        returns
            ({
                use vest_lib2::asn1::der::{DEFAULT, OCTET_STRING, SEQUENCE};
                Mapped {
                    inner:
                        SEQUENCE(
                            DEFAULT(VERSION::Fmt, 0i8,
                            REQUIRED(Ref(OCTET_STRING),
                            Eof)),
                        ),
                    mapper: BiMap(SharedForward, SharedReverse),
                }
            }),
    {
        use vest_lib2::asn1::der::{DEFAULT, OCTET_STRING, SEQUENCE};
        Mapped {
            inner:
                SEQUENCE(
                    DEFAULT(VERSION::Fmt, 0i8,
                    REQUIRED(Ref(OCTET_STRING),
                    Eof)),
                ),
            mapper: BiMap(SharedForward, SharedReverse),
        }
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0001000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(asn1_starts_disjoint);
        reveal(SHARED::spec_inner);
        lemma_asn1_start_exact_uint(self.0, true, self.1);
        let __asn1_fmt_0 =
            VERSION::Fmt;
        assert(__asn1_fmt_0.asn1_start() == asn1_start_exact_uint(Class::Universal, false, 2u64));
        assert(asn1_start_exact_uint(Class::Universal, false, 2u64) == asn1_start_mask(false, 0x0000000000000004u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
        let __asn1_fmt_1 =
            REQUIRED(Ref(vest_lib2::asn1::der::OCTET_STRING),
            Eof);
        let __asn1_fmt_2 =
            Ref(vest_lib2::asn1::der::OCTET_STRING);
        let __asn1_fmt_3 =
            vest_lib2::asn1::der::OCTET_STRING;
        assert(__asn1_fmt_3.asn1_start() == asn1_start_exact_uint(Class::Universal, false, 4u64));
        assert(asn1_start_exact_uint(Class::Universal, false, 4u64) == asn1_start_mask(false, 0x0000000000000010u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
        assert(__asn1_fmt_2.asn1_start() == asn1_start_exact_uint(Class::Universal, false, 4u64));
        assert(__asn1_fmt_1.asn1_start() == asn1_start_exact_uint(Class::Universal, false, 4u64));
        assert(asn1_starts_disjoint(asn1_start_mask(false, 0x0000000000000004u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64), asn1_start_mask(false, 0x0000000000000010u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64))) by (bit_vector);
        assert(asn1_starts_disjoint(__asn1_fmt_0.asn1_start(), __asn1_fmt_1.asn1_start()));
        lemma_disjoint_asn1_starts(__asn1_fmt_0, __asn1_fmt_1);
        assert forall|output: <SharedForward as SpecMap>::Output| #[trigger]
            self.spec_inner().consistent(output) implies self.spec_inner().mapper.sound(output) by {
            if self.spec_inner().consistent(output) {
                SharedSpec::lemma_from_into(output);
            }
        }
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0001000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// DER format for ASN.1 `Canonical`.
type CANONICAL__ = vest_lib2::asn1::der::SetOfTlvFmt<SHARED>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct CANONICAL(pub Class, pub u64);
impl CANONICAL {
    pub const Fmt: Self = Self(Class::Universal, 17u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> CANONICAL__
        returns
            ({
                use vest_lib2::asn1::der::SET_OF;
                SET_OF(SHARED::Fmt)
            }),
    {
        use vest_lib2::asn1::der::SET_OF;
        SET_OF(SHARED::Fmt)
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0002000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(CANONICAL::spec_inner);
        lemma_asn1_start_exact_uint(self.0, true, self.1);
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0002000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// DER format for ASN.1 `Ordered`.
type ORDERED__ = Mapped<vest_lib2::asn1::der::SetFmt<Pair<ImplicitFmt<Ref<vest_lib2::asn1::der::BoolTlvFmt>>, Optional<ImplicitFmt<Ref<vest_lib2::asn1::der::IntegerTlvFmt>>, Eof>>>, BiMap<OrderedForward, OrderedReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct ORDERED(pub Class, pub u64);
impl ORDERED {
    pub const Fmt: Self = Self(Class::Universal, 17u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> ORDERED__
        returns
            ({
                use vest_lib2::asn1::der::{BOOLEAN, INTEGER, SET};
                Mapped {
                    inner:
                        SET(
                            REQUIRED(IMPLICIT(0u64, Ref(BOOLEAN)),
                            OPTIONAL(IMPLICIT(1u64, Ref(INTEGER)),
                            Eof)),
                        ),
                    mapper: BiMap(OrderedForward, OrderedReverse),
                }
            }),
    {
        use vest_lib2::asn1::der::{BOOLEAN, INTEGER, SET};
        Mapped {
            inner:
                SET(
                    REQUIRED(IMPLICIT(0u64, Ref(BOOLEAN)),
                    OPTIONAL(IMPLICIT(1u64, Ref(INTEGER)),
                    Eof)),
                ),
            mapper: BiMap(OrderedForward, OrderedReverse),
        }
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0002000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(asn1_start_empty);
        reveal(asn1_starts_disjoint);
        reveal(ORDERED::spec_inner);
        lemma_asn1_start_exact_uint(self.0, true, self.1);
        let __asn1_fmt_0 =
            IMPLICIT(1u64, Ref(vest_lib2::asn1::der::INTEGER));
        assert(__asn1_fmt_0.asn1_start() == asn1_start_exact_uint(Class::ContextSpecific, false, 1u64));
        assert(asn1_start_exact_uint(Class::ContextSpecific, false, 1u64) == asn1_start_mask(false, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000002u64, 0x0000000000000000u64)) by (bit_vector);
        let __asn1_fmt_1 =
            Eof;
        assert(__asn1_fmt_1.asn1_start() == asn1_start_mask(true, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64));
        assert(asn1_starts_disjoint(asn1_start_mask(false, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000002u64, 0x0000000000000000u64), asn1_start_mask(true, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64))) by (bit_vector);
        assert(asn1_starts_disjoint(__asn1_fmt_0.asn1_start(), __asn1_fmt_1.asn1_start()));
        lemma_disjoint_asn1_starts(__asn1_fmt_0, __asn1_fmt_1);
        assert forall|output: <OrderedForward as SpecMap>::Output| #[trigger]
            self.spec_inner().consistent(output) implies self.spec_inner().mapper.sound(output) by {
            if self.spec_inner().consistent(output) {
                OrderedSpec::lemma_from_into(output);
            }
        }
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0002000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// BER format for ASN.1 `Outer`.
type OUTER__ = Mapped<vest_lib2::asn1::ber::SequenceFmt<Pair<Ref<SHARED>, Pair<ImplicitFmt<Ref<CANONICAL>>, Pair<vest_lib2::asn1::ber::ExplicitFmt<Ref<ORDERED>>, Optional<Ref<vest_lib2::asn1::ber::AnyTlvFmt>, vest_lib2::asn1::ber::BerEndFmt>>>>>, BiMap<OuterForward, OuterReverse>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct OUTER(pub Class, pub u64);
impl OUTER {
    pub const Fmt: Self = Self(Class::Universal, 16u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> OUTER__
        returns
            ({
                use vest_lib2::asn1::ber::{ANY, BER_END, EXPLICIT, SEQUENCE};
                Mapped {
                    inner:
                        SEQUENCE(
                            REQUIRED(Ref(SHARED::Fmt),
                            REQUIRED(IMPLICIT(0u64, Ref(CANONICAL::Fmt)),
                            REQUIRED(EXPLICIT(1u64, Ref(ORDERED::Fmt)),
                            OPTIONAL(Ref(ANY),
                            BER_END)))),
                        ),
                    mapper: BiMap(OuterForward, OuterReverse),
                }
            }),
    {
        use vest_lib2::asn1::ber::{ANY, BER_END, EXPLICIT, SEQUENCE};
        Mapped {
            inner:
                SEQUENCE(
                    REQUIRED(Ref(SHARED::Fmt),
                    REQUIRED(IMPLICIT(0u64, Ref(CANONICAL::Fmt)),
                    REQUIRED(EXPLICIT(1u64, Ref(ORDERED::Fmt)),
                    OPTIONAL(Ref(ANY),
                    BER_END)))),
                ),
            mapper: BiMap(OuterForward, OuterReverse),
        }
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0001000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(asn1_start_any_non_eoc);
        reveal(asn1_starts_disjoint);
        reveal(OUTER::spec_inner);
        lemma_asn1_start_exact_uint(self.0, true, self.1);
        let __asn1_fmt_0 =
            Ref(vest_lib2::asn1::ber::ANY);
        let __asn1_fmt_1 =
            vest_lib2::asn1::ber::ANY;
        assert(__asn1_fmt_1.asn1_start() == asn1_start_mask(false, 0xfffffffffffffffeu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64));
        assert(__asn1_fmt_0.asn1_start() == asn1_start_mask(false, 0xfffffffffffffffeu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64));
        let __asn1_fmt_2 =
            vest_lib2::asn1::ber::BER_END;
        reveal(asn1_start_ber_boundary);
        assert(asn1_start_ber_boundary() == asn1_start_mask(true, 0x0000000000000001u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
        assert(__asn1_fmt_2.asn1_start() == asn1_start_ber_boundary());
        assert(asn1_starts_disjoint(asn1_start_mask(false, 0xfffffffffffffffeu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64, 0xffffffffffffffffu64), asn1_start_mask(true, 0x0000000000000001u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64))) by (bit_vector);
        assert(asn1_starts_disjoint(__asn1_fmt_0.asn1_start(), __asn1_fmt_2.asn1_start()));
        lemma_disjoint_asn1_starts(__asn1_fmt_0, __asn1_fmt_2);
        assert forall|output: <OuterForward as SpecMap>::Output| #[trigger]
            self.spec_inner().consistent(output) implies self.spec_inner().mapper.sound(output) by {
            if self.spec_inner().consistent(output) {
                OuterSpec::lemma_from_into(output);
            }
        }
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0001000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// BER format for ASN.1 `NumericLabel`.
type NUMERIC_LABEL__ = Refined<vest_lib2::asn1::ber::NumericStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct NUMERIC_LABEL(pub Class, pub u64);
impl NUMERIC_LABEL {
    pub const Fmt: Self = Self(Class::Universal, 18u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> NUMERIC_LABEL__
        returns
            ({
                use vest_lib2::asn1::ber::NUMERIC_STRING;
                Refined(NUMERIC_STRING, Size::<true, 1, true, 16>)
            }),
    {
        use vest_lib2::asn1::ber::NUMERIC_STRING;
        Refined(NUMERIC_STRING, Size::<true, 1, true, 16>)
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0004000000040000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(NUMERIC_LABEL::spec_inner);
        lemma_asn1_start_identity_uint(self.0, self.1);
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x0004000000040000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}

/// BER format for ASN.1 `UniversalLabel`.
type UNIVERSAL_LABEL__ = Refined<vest_lib2::asn1::ber::UniversalStringTlvFmt, Size<true, 1, true, 16>>;
#[derive(Clone, Copy)]
#[verifier::ext_equal]
pub struct UNIVERSAL_LABEL(pub Class, pub u64);
impl UNIVERSAL_LABEL {
    pub const Fmt: Self = Self(Class::Universal, 28u64);

    #[verifier::allow_in_spec]
    pub const fn schema() -> UNIVERSAL_LABEL__
        returns
            ({
                use vest_lib2::asn1::ber::UNIVERSAL_STRING;
                Refined(UNIVERSAL_STRING, Size::<true, 1, true, 16>)
            }),
    {
        use vest_lib2::asn1::ber::UNIVERSAL_STRING;
        Refined(UNIVERSAL_STRING, Size::<true, 1, true, 16>)
    }

    proof fn lemma_schema_unambiguous(&self)
        ensures
            self.spec_inner().unambiguous(),
            self.spec_inner().asn1_start() == self.asn1_start(),
            Self::Fmt.asn1_start() == asn1_start_mask(false, 0x1000000010000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64),
    {
        reveal(asn1_start_exact_uint);
        reveal(UNIVERSAL_LABEL::spec_inner);
        lemma_asn1_start_identity_uint(self.0, self.1);
        assert(self.spec_inner().asn1_start() == self.asn1_start());
        assert(Self::Fmt.asn1_start() == asn1_start_mask(false, 0x1000000010000000u64, 0x0000000000000000u64, 0x0000000000000000u64, 0x0000000000000000u64)) by (bit_vector);
    }
}


} // verus!

mod __impl_version {
    use super::*;

    vest_lib2::impl_der!(tagged_exact(false), owned, VERSION, VERSION__, VersionSpec, Version);
}

mod __impl_shared {
    use super::*;

    vest_lib2::impl_der!(tagged_exact(true), borrowed, SHARED, SHARED__, SharedSpec, Shared, SharedForward, SharedReverse);
}

mod __impl_canonical {
    use super::*;

    vest_lib2::impl_der!(tagged_exact(true), borrowed, CANONICAL, CANONICAL__, CanonicalSpec, Canonical);
}

mod __impl_ordered {
    use super::*;

    vest_lib2::impl_der!(tagged_exact(true), borrowed, ORDERED, ORDERED__, OrderedSpec, Ordered, OrderedForward, OrderedReverse);
}

mod __impl_outer {
    use super::*;

    vest_lib2::impl_ber!(tagged_exact(true), borrowed, OUTER, OUTER__, OuterSpec, Outer, OuterForward, OuterReverse);
}

mod __impl_numeric_label {
    use super::*;

    vest_lib2::impl_ber!(tagged_identity(false), owned, NUMERIC_LABEL, NUMERIC_LABEL__, NumericLabelSpec, NumericLabel);
}

mod __impl_universal_label {
    use super::*;

    vest_lib2::impl_ber!(tagged_identity(false), owned, UNIVERSAL_LABEL, UNIVERSAL_LABEL__, UniversalLabelSpec, UniversalLabel);
}
