//! Integration tests for the v2 code generator.
//!
//! These tests use pre-generated Rust code from vest files located in `tests/emitted/`.
//! To regenerate the emitted files, run:
//!   cargo run -- tests/vest_files/combined.vest -o tests/emitted/combined.rs
//!   cargo run -- tests/vest_files/tlv.vest -o tests/emitted/tlv.rs

mod emitted;

use emitted::combined;
use emitted::tlv;
use vest_lib::properties::{Combinator, GenSt};

#[test]
fn combined_generate_serialize_parse_roundtrip() {
    let mut comb = combined::Packet();

    for seed in 0..16u64 {
        let (reported_len, value): (usize, combined::Packet) = comb
            .generate(&mut GenSt::new(seed))
            .expect("generate packet");

        let payload_len = value.field1 as usize;
        assert_eq!(
            payload_len,
            value.payload.len() * 8,
            "seed {seed}: payload_len should equal the serialized record bytes",
        );

        let computed_len =
            <combined::PacketCombinator as Combinator<[u8], Vec<u8>>>::length(&comb, &value);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );

        let mut buf = vec![0u8; computed_len];
        let written = combined::serialize_Packet(&value, &mut buf, 0).expect("serialize packet");
        assert_eq!(written, computed_len);
        assert_eq!(
            &buf[..2],
            &[0xFE, 0xCA],
            "seed {seed}: current DSL lowering emits the magic tag in little endian",
        );

        let (consumed, parsed) = combined::parse_Packet(&buf).expect("parse packet");
        assert_eq!(consumed, written);
        assert_eq!(parsed, value);
    }
}

#[test]
fn tlv_dispatch_branches_parse() {
    let tag1_payload = [0xAB; 32];
    let (_, parsed1) = tlv::parse_msg_val(&tag1_payload, 32, 1).expect("parse msg1 payload");
    match parsed1 {
        tlv::MsgVal::Variant0(bytes) => assert_eq!(bytes, &tag1_payload),
        _ => panic!("expected msg1 branch"),
    }

    let mut tag3_payload = Vec::new();
    tag3_payload.extend_from_slice(&0x1234u16.to_le_bytes());
    tag3_payload.extend_from_slice(&0x5678u16.to_le_bytes());
    let (_, parsed3) = tlv::parse_msg_val(&tag3_payload, 4, 3).expect("parse msg3 payload");
    match parsed3 {
        tlv::MsgVal::Variant2(msg3) => {
            assert_eq!(msg3.x, 0x1234);
            assert_eq!(msg3.y, 0x5678);
        }
        _ => panic!("expected msg3 branch"),
    }
}

#[test]
fn tlv_msg_generate_roundtrip() {
    let mut comb = tlv::msg();

    for seed in 0..16u64 {
        let (reported_len, value) = comb.generate(&mut GenSt::new(seed)).expect("generate msg");
        let stype_val = match &value.val {
            tlv::MsgValOwned::Variant0(bytes) => tlv::MsgVal::Variant0(bytes.as_slice()),
            tlv::MsgValOwned::Variant1(pkt) => tlv::MsgVal::Variant1(pkt.clone()),
            tlv::MsgValOwned::Variant2(msg3) => tlv::MsgVal::Variant2(msg3.clone()),
        };
        let stype = tlv::Msg {
            tag: value.tag,
            len: value.len,
            val: stype_val,
        };

        let computed_len = <tlv::MsgCombinator as Combinator<[u8], Vec<u8>>>::length(&comb, &stype);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );

        let mut buf = vec![0u8; computed_len];
        let written = tlv::serialize_msg(&stype, &mut buf, 0).expect("serialize msg");
        assert_eq!(written, computed_len);

        let (consumed, parsed) = tlv::parse_msg(&buf).expect("parse msg");
        assert_eq!(consumed, written);
        assert_eq!(parsed, stype);
    }
}
