//! Integration tests for the current Rust code generator.
//!
//! These tests use pre-generated Rust code from vest files located in `tests/emitted/`.
//! To regenerate the emitted files, run:
//!   cargo run -- tests/vest_files/combined.vest -o tests/emitted/combined.rs
//!   cargo run -- tests/vest_files/tlv.vest -o tests/emitted/tlv.rs

mod emitted;

use emitted::combined;
use emitted::tlv;
use vest_lib::properties::GenSt;

#[test]
fn combined_generate_serialize_parse_roundtrip() {
    for seed in 0..16u64 {
        let (reported_len, value): (usize, combined::Packet) =
            combined::generate_Packet(&mut GenSt::new(seed)).expect("generate packet");

        let payload_len = value.payload_len as usize;
        assert_eq!(
            payload_len,
            value.payload.len() * 8,
            "seed {seed}: payload_len should equal the serialized record bytes",
        );

        let computed_len = combined::Packet_len(&value);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );

        let mut buf = vec![0u8; computed_len];
        let written = combined::serialize_Packet(&value, &mut buf, 0).expect("serialize packet");
        assert_eq!(written, computed_len);
        assert_eq!(
            &buf[..2],
            &[0xFE, 0xCA],
            "seed {seed}: current DSL lowering emits the magic tag in little endian",
        );

        let (consumed, parsed) = combined::parse_Packet(&buf).expect("parse packet");
        assert_eq!(consumed, written);
        assert_eq!(parsed, value);
    }
}

#[test]
fn tlv_msg_generate_roundtrip() {
    for seed in 0..16u64 {
        let (reported_len, value) = tlv::generate_msg(&mut GenSt::new(seed)).expect("generate msg");
        let stype_val = match &value.val {
            tlv::MsgValOwned::Ty1(bytes) => tlv::MsgVal::Ty1(bytes.as_slice()),
            tlv::MsgValOwned::Ty2(pkt) => tlv::MsgVal::Ty2(pkt.clone()),
            tlv::MsgValOwned::Ty3(msg3) => tlv::MsgVal::Ty3(msg3.clone()),
        };
        let stype = tlv::Msg {
            tag: value.tag,
            len: value.len,
            val: stype_val,
        };

        let computed_len = tlv::msg_len(&stype);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );

        let mut buf = vec![0u8; computed_len];
        let written = tlv::serialize_msg(&stype, &mut buf, 0).expect("serialize msg");
        assert_eq!(written, computed_len);

        let (consumed, parsed) = tlv::parse_msg(&buf).expect("parse msg");
        assert_eq!(consumed, written);
        assert_eq!(parsed, stype);
    }
}
