pub mod transaction_data;
pub mod vest_bitcoin {
    // This module includes the code generated by the build script from src/bitcoin.vest
    // The generated file is placed in OUT_DIR/bitcoin.rs by build.rs
    include!(concat!(env!("OUT_DIR"), "/bitcoin.rs"));
}
