[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = "=0.0.0-2026-07-27-0206"

vest_lib2 = { path = "../../vest_lib2" }

[features]
projected-argument-deref-regression = []

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
base64 = "0.22.1"
bitcoin = "0.32.100"
rustls = "0.22"

[[bench]]
name = "generated_parser_benchmark"
harness = false

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--expand-errors"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(verus_only)"] }
